#ifndef IN_GAME_MPLAYER_MPLAYER_H
#define IN_GAME_MPLAYER_MPLAYER_H
#include "data.h"
#include "types.h"

float mpHandicapToDamageScale(uint8_t value);
void func0f187838(struct mpchrconfig *mpchr);
void mpStartMatch(void);
void mpReset(void);
void mpCalculateTeamIsOnlyAi(void);
void func0f187fbc(int playernum);
void mpSetScoringDefaults(void);
void mpPlayerSetDefaults(int playernum, bool autonames);
void func0f1881d4(int index);
void mpInit(void);
void mpGetTeamsWithDefaultName(uint8_t *mask);
void mpSetTeamNamesToDefault(uint8_t mask);
void mpSetDefaultNamesIfEmpty(void);
int mpCalculateTeamScoreLimit(void);
void mpApplyLimits(void);
int mpGetPlayerRankings(struct ranking *rankings);
int mpCalculateTeamScore(int arg0, int *arg1);
int mpGetTeamRankings(struct ranking *rankings);
int mpGetNumWeaponOptions(void);
char *mpGetWeaponLabel(int weaponnum);
void mpSetWeaponSlot(int slot, int mpweaponnum);
int mpGetWeaponSlot(int slot);
struct mpweapon *mpGetMpWeaponByLocation(int locationindex);
int mpCountWeaponSetThing(int weaponsetindex);
int func0f188f9c(int arg0);
int func0f189058(bool full);
int func0f189088(void);
char *mpGetWeaponSetName(int arg0);
void func0f18913c(void);
#ifndef PLATFORM_N64
void mpSetRandomWeapons(uint8_t weapons[]);
#endif
void mpApplyWeaponSet(void);
void mpSetWeaponSet(int weaponsetnum);
void mpApplyWeaponSetIfValid(void);
int mpGetWeaponSet(void);
bool mpIsPaused(void);
void mpSetPaused(uint8_t mode);
Gfx *mpRenderModalText(Gfx *gdl);
int mpFindMaxInt(int playercount, int val0, int val1, int val2, int val3);
int mpFindMinInt(int playercount, int val0, int val1, int val2, int val3);
int mpFindMaxFloat(int playercount, float val0, float val1, float val2, float val3);
int mpFindMinFloat(int playercount, float val0, float val1, float val2, float val3);
void mpCalculatePlayerTitle(struct mpplayerconfig *mpplayer);
void mpCalculateAwards(void);
void mpEndMatch(void);
int mpGetNumHeads2(void);
int mpGetNumHeads(void);
int mpGetHeadId(uint8_t headnum);
int mpGetHeadRequiredFeature(uint8_t headnum);
int mpGetBeauHeadId(uint8_t headnum);
uint32_t mpGetNumBodies(void);
int mpGetBodyId(uint8_t bodynum);
int mpGetMpbodynumByBodynum(uint16_t bodynum);
char *mpGetBodyName(uint8_t mpbodynum);
uint8_t mpGetBodyRequiredFeature(uint8_t bodynum);
int mpGetMpheadnumByMpbodynum(int bodynum);
int mpChooseRandomLockPlayer(void);
bool mpSetLock(int locktype, int playernum);
int mpGetLockType(void);
uint32_t mpGetLockPlayerNum(void);
bool mpIsPlayerLockedOut(int playernum);
void mpCalculateLockIfLastWinnerOrLoser(void);
bool mpIsTrackUnlocked(int tracknum);
int mpGetTrackSlotIndex(int tracknum);
int mpGetTrackNumAtSlotIndex(int slotindex);
int mpGetNumUnlockedTracks(void);
int mpGetTrackMusicNum(int slotindex);
char *mpGetTrackName(int slotindex);
void mpSetUsingMultipleTunes(bool enable);
bool mpGetUsingMultipleTunes(void);
bool mpIsMultiTrackSlotEnabled(int slot);
void mpSetMultiTrackSlotEnabled(int slot, bool enable);
void mpSetTrackSlotEnabled(int slot);
void mpEnableAllMultiTracks(void);
void mpDisableAllMultiTracks(void);
void mpRandomiseMultiTracks(void);
void mpSetTrackToRandom(void);
int mpGetCurrentTrackSlotNum(void);
int mpChooseTrack(void);
struct mpchrconfig *mpGetChrConfigBySlotNum(int slot);
int mpGetChrIndexBySlotNum(int slot);
int mpGetNumChrs(void);
uint8_t mpFindUnusedTeamNum(void);
void mpCreateBotFromProfile(int botnum, uint8_t difficulty);
void mpSetBotDifficulty(int botnum, int difficulty);
int mpGetSlotForNewBot(void);
void mpRemoveSimulant(int index);
void mpCopySimulant(int index);
bool mpHasSimulants(void);
bool mpHasUnusedBotSlots(void);
bool mpIsSimSlotEnabled(int slot);
int mpFindBotProfile(int type, int difficulty);
void mpGenerateBotNames(void);
int mpPlayerGetIndex(struct chrdata *chr);
struct chrdata *mpGetChrFromPlayerIndex(int index);
int func0f18d074(int index);
int func0f18d0e8(int arg0);
void mpplayerfileLoadGunFuncs(struct savebuffer *buffer, int playernum);
void mpplayerfileSaveGunFuncs(struct savebuffer *buffer, int playernum);
void mpplayerfileLoadWad(int playernum, struct savebuffer *buffer, int arg2);
void mpplayerfileSaveWad(int playernum, struct savebuffer *buffer);
void mpplayerfileGetOverview(char *arg0, char *name, uint32_t *playtime);
int mpplayerfileSave(int playernum, int device, int fileid, uint16_t deviceserial);
int mpplayerfileLoad(int playernum, int device, int arg2, uint16_t deviceserial);
int mpGetNumPresets(void);
bool mpIsPresetUnlocked(int presetnum);
int mpGetNumUnlockedPresets(void);
char *mpGetPresetNameBySlot(int slot);
void mpApplyConfig(struct mpconfigfull *mpconfig);
void mp0f18dec4(int arg0);
void mpsetupfileLoadWad(struct savebuffer *buffer);
void mpsetupfileSaveWad(struct savebuffer *buffer);
void mpsetupfileGetOverview(char *arg0, char *filename, uint16_t *numsims, uint16_t *stagenum, uint16_t *scenarionum);
int mpsetupfileSave(int device, int filenum, uint16_t deviceserial);
int mpsetupfileLoad(int device, int filenum, uint16_t deviceserial);
void mpResetHeads(void);
struct modeldef *mpClearHeads(int index, int *headnum);

#endif
