#ifndef _IN_GAME_MPLAYER_SETUP_H
#define _IN_GAME_MPLAYER_SETUP_H
#include "data.h"
#include "types.h"

char *mpGetCurrentPlayerName(struct menuitem *item);
int16_t mpChooseRandomStage(void);
MenuItemHandlerResult mpArenaMenuHandler(int operation, struct menuitem *item, union handlerdata *data);
char *mpMenuTextWeaponNameForSlot(struct menuitem *item);
char *mpMenuTextSetupName(struct menuitem *item);
MenuItemHandlerResult mpCharacterBodyMenuHandler(int operation, struct menuitem *item, union handlerdata *data, int mpbodynum, int mpheadnum, bool isplayer);
MenuDialogHandlerResult menudialog0017a174(int operation, struct menudialogdef *dialogdef, union handlerdata *data);
MenuItemHandlerResult mpChallengesListHandler(int operation, struct menuitem *item, union handlerdata *data);
char *mpMenuTextKills(struct menuitem *item);
char *mpMenuTextDeaths(struct menuitem *item);
char *mpMenuTextGamesPlayed(struct menuitem *item);
char *mpMenuTextGamesWon(struct menuitem *item);
char *mpMenuTextGamesLost(struct menuitem *item);
char *mpMenuTextHeadShots(struct menuitem *item);
char *mpMenuTextMedalAccuracy(struct menuitem *item);
char *mpMenuTextMedalHeadShot(struct menuitem *item);
char *mpMenuTextMedalKillMaster(struct menuitem *item);
char *mpMenuTextMedalSurvivor(struct menuitem *item);
char *mpMenuTextAmmoUsed(struct menuitem *item);
char *mpMenuTextDistance(struct menuitem *item);
char *mpMenuTextTime(struct menuitem *item);
char *mpMenuTextAccuracy(struct menuitem *item);
void mpFormatDamageValue(char *dst, float damage);
char *mpMenuTextPainReceived(struct menuitem *item);
char *mpMenuTextDamageDealt(struct menuitem *item);
MenuItemHandlerResult mpMedalMenuHandler(int operation, struct menuitem *item, union handlerdata *data);
char *mpMenuTitleStatsForPlayerName(struct menudialogdef *dialogdef);
char *mpMenuTextUsernamePassword(struct menuitem *item);
MenuItemHandlerResult mpCharacterHeadMenuHandler(int operation, struct menuitem *item, union handlerdata *data, int mpheadnum, bool arg4);
char *mpMenuTextBodyName(struct menuitem *item);
void func0f17b8f0(void);
MenuItemHandlerResult mpPlayerNameMenuHandler(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult mpLoadSettingsMenuHandler(int operation, struct menuitem *item, union handlerdata *data);
char *mpMenuTextMpconfigMarquee(struct menuitem *item);
MenuItemHandlerResult mpLoadPlayerMenuHandler(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpHandicapPlayer(int operation, struct menuitem *item, union handlerdata *data);
char *mpMenuTextHandicapPlayerName(struct menuitem *item);
MenuItemHandlerResult mpAddChangeSimulantMenuHandler(int operation, struct menuitem *item, union handlerdata *data);
char *mpMenuTextSimulantDescription(struct menuitem *item);
MenuDialogHandlerResult menudialog0017ccfc(int operation, struct menudialogdef *dialogdef, union handlerdata *data);
MenuItemHandlerResult mpBotDifficultyMenuHandler(int operation, struct menuitem *item, union handlerdata *data);
char *mpMenuTitleEditSimulant(struct menudialogdef *dialogdef);
char *mpMenuTextSimulantName(struct menuitem *item);
MenuItemHandlerResult menuhandlerMpNTeams(int operation, struct menuitem *item, union handlerdata *data, int numteams);
char *mpMenuTextChrNameForTeamSetup(struct menuitem *item);
MenuItemHandlerResult func0f17dac4(int operation, struct menuitem *item, union handlerdata *data);
char *mpMenuTextSelectTuneOrTunes(struct menuitem *item);
MenuItemHandlerResult mpSelectTuneListHandler(int operation, struct menuitem *item, union handlerdata *data);
char *mpMenuTextCurrentTrack(struct menuitem *item);
MenuItemHandlerResult mpTeamNameMenuHandler(int operation, struct menuitem *item, union handlerdata *data);
char *mpMenuTextTeamName(struct menuitem *item);
char *func0f17e318(struct menudialogdef *dialogdef);
MenuDialogHandlerResult menudialog0017e3fc(int operation, struct menudialogdef *dialogdef, union handlerdata *data);
MenuItemHandlerResult mpChallengesListMenuHandler(int operation, struct menuitem *item, union handlerdata *data);
char *mpMenuTextChallengeName(struct menuitem *item);
MenuDialogHandlerResult mpCombatChallengesMenuDialog(int operation, struct menudialogdef *dialogdef, union handlerdata *data);
char *mpMenuTextSavePlayerOrCopy(struct menuitem *item);
char *mpMenuTextArenaName(struct menuitem *item);
char *mpMenuTextWeaponSetName(struct menuitem *item);
void mpConfigureQuickTeamPlayers(void);
void mpConfigureQuickTeamSimulants(void);
void func0f17f428(void);
MenuItemHandlerResult menuhandlerPlayerTeam(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpNumberOfSimulants(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpSimulantsPerTeam(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult mpQuickTeamSimulantDifficultyHandler(int operation, struct menuitem *item, union handlerdata *data);
void mpCloseDialogsForNewSetup(void);
void func0f17fcb0(int silent);
MenuItemHandlerResult menuhandlerMpSlowMotion(int operation, struct menuitem *item, union handlerdata *data);
void htbAddPad(int16_t padnum);
void htbRemoveAmmoCrateAtPad(int16_t padnum);
void htbReset(void);
void htbCreateToken(void);
Gfx *htbRenderHud(Gfx *gdl);
void ctcInitProps(void);
bool ctcHighlightProp(struct prop *prop, int *colour);
void ctcAddPad(int *cmd);
void ctcHighlightRoom(RoomNum roomnum, int *arg1, int *arg2, int *arg3);
void kohTick(void);
Gfx *kohRenderHud(Gfx *gdl);
void kohAddHill(int *cmd);
void kohHighlightRoom(RoomNum roomnum, int *arg1, int *arg2, int *arg3);
void htmAddPad(int16_t padnum);
void htmReset(void);
void htbCreateUplink(void);
void htmInitProps(void);
void htmTickChr(struct chrdata *chr);
Gfx *htmRenderHud(Gfx *gdl);
Gfx *htmRadarExtra(Gfx *gdl);
void pacReset(void);
bool pacHighlightProp(struct prop *prop, int *colour);
void pacApplyNextVictim(void);
void pacHandleDeath(int cplayernum, int vplayernum);
void pacTick(void);
Gfx *pacRenderHud(Gfx *gdl);
bool pacRadarChr(Gfx **gdl, struct prop *prop);
MenuDialogHandlerResult mpOptionsMenuDialog(int operation, struct menudialogdef *dialogdef, union handlerdata *data);
char *mpMenuTextScenarioShortName(struct menuitem *item);
char *mpMenuTextScenarioName(struct menuitem *item);
MenuItemHandlerResult scenarioScenarioMenuHandler(int operation, struct menuitem *item, union handlerdata *data);
void scenarioCreateMatchStartHudmsgs(void);
Gfx *scenarioRenderHud(Gfx *gdl);
void scenarioCalculatePlayerScore(struct mpchrconfig *mpchr, int chrnum, int *arg2, int *arg3);
bool scenarioHighlightProp(struct prop *prop, int *colour);
void scenarioReset(void);
struct prop *scenarioCreateObj(int modelnum, int16_t padnum, float arg2, uint32_t flags, uint32_t flags2, uint32_t flags3);
void scenarioCreateHudmsg(int playernum, char *message);
bool scenarioChrsAreSameTeam(int playernum1, int playernum2);
int scenarioPickUpBriefcase(struct chrdata *chr, struct prop *prop);
void scenarioHandleDroppedToken(struct chrdata *chr, struct prop *prop);
int scenarioPickUpUplink(struct chrdata *chr, struct prop *prop);
void scenarioHandleActivatedProp(struct chrdata *chr, struct prop *prop);
MenuItemHandlerResult menuhandlerMpDropOut(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpTeamsLabel(int operation, struct menuitem *item, union handlerdata *data);
int mpGetNumStages(void);
MenuItemHandlerResult menuhandlerMpControlStyle(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpWeaponSlot(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpWeaponSetDropdown(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpControlCheckbox(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpAimControl(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpCheckboxOption(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpTeamsEnabled(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpDisplayOptionCheckbox(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpConfirmSaveChr(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpSetupName(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpSaveSetupOverwrite(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpSaveSetupCopy(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpCharacterBody(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpUsernamePassword(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpCharacterHead(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpTimeLimitSlider(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpScoreLimitSlider(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpTeamScoreLimitSlider(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpRestoreScoreDefaults(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpRestoreHandicapDefaults(int operation, struct menuitem *item, union handlerdata *data);
MenuDialogHandlerResult menudialogMpReady(int operation, struct menudialogdef *dialogdef, union handlerdata *data);
MenuDialogHandlerResult menudialogMpSimulant(int operation, struct menudialogdef *dialogdef, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpSimulantHead(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpSimulantBody(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpDeleteSimulant(int operation, struct menuitem *item, union handlerdata *data);
#ifndef PLATFORM_N64
MenuItemHandlerResult menuhandlerMpCopySimulant(int operation, struct menuitem *item, union handlerdata *data);
#endif
MenuItemHandlerResult menuhandlerMpChangeSimulantType(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpClearAllSimulants(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpAddSimulant(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpSimulantSlot(int operation, struct menuitem *item, union handlerdata *data);
MenuDialogHandlerResult menudialogMpSimulants(int operation, struct menudialogdef *dialogdef, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpTwoTeams(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpThreeTeams(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpFourTeams(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpMaximumTeams(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpHumansVsSimulants(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpHumanSimulantPairs(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpTeamSlot(int operation, struct menuitem *item, union handlerdata *data);
MenuDialogHandlerResult menudialogMpSelectTune(int operation, struct menudialogdef *dialogdef, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpMultipleTunes(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpTeamNameSlot(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandler0017e38c(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandler0017e9d8(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpAbortChallenge(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpStartChallenge(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandler0017ec64(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpLock(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpSavePlayer(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandler0017ef30(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpSaveSettings(int operation, struct menuitem *item, union handlerdata *data);
MenuDialogHandlerResult menudialogMpGameSetup(int operation, struct menudialogdef *dialogdef, union handlerdata *data);
MenuDialogHandlerResult menudialogMpQuickGo(int operation, struct menudialogdef *dialogdef, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpFinishedSetup(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerQuickTeamSeparator(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpQuickTeamOption(int operation, struct menuitem *item, union handlerdata *data);
MenuDialogHandlerResult menudialogCombatSimulator(int operation, struct menudialogdef *dialogdef, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpAdvancedSetup(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpDisplayTeam(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMpOneHitKills(int operation, struct menuitem *item, union handlerdata *data);

#endif
