/**************************************************************************
 *                                                                        *
 *               Copyright (C) 1994, Silicon Graphics, Inc.               *
 *                                                                        *
 *  These coded instructions, statements, and computer programs  contain  *
 *  unpublished  proprietary  information of Silicon Graphics, Inc., and  *
 *  are protected by Federal copyright law.  They  may  not be disclosed  *
 *  to  third  parties  or copied or duplicated in any form, in whole or  *
 *  in part, without the prior written consent of Silicon Graphics, Inc.  *
 *                                                                        *
 **************************************************************************/
/**************************************************************************
 *
 *  $Revision: 1.138 $
 *  $Date: 1998/12/24 09:05:08 $
 *  $Source: /hosts/gate3/exdisk2/cvs/N64OS/Master/cvsmdev2/PR/include/gbi.h,v $
 *
 **************************************************************************/

#ifndef _GBI_H_
#define _GBI_H_

#include <stdint.h>
#include "platform.h"

/*
 * To use the F3DEX ucodes, define F3DEX_GBI before include this file.
 *
 *     #define  F3DEX_GBI
 *     #include <ultra64.h>
 *
 *     or
 *
 *     cc -c -DF3DEX_GBI -I.... foo.c
 *
 */

/**************************************************************************
 *
 * Graphics Binary Interface
 *
 **************************************************************************/

/*
 * Graphics Commands, 'xxx' parts may be generated from ucode
 *
 * The command format is
 *
 *  |00xxxxxx| = DMA            0,..,127
 *  |10xxxxxx| = Immediate Mode -65,..,-128
 *  |11xxxxxx| = RDP cmds       -1,..,-64
 *
 * Note: in order for the RSP microcode to process RDP commands opaquely,
 * we need to further identify those RDP commands that need DRAM address
 * "fixup". To do this, we have the dummy command G_RDP_ADDR_FIXUP, and
 * all |RDP commands| less than this are commands with embedded DRAM
 * addresses. Further, the format of these commands should be similar so
 * only one fixup routine is needed.
 *
 * Further explanation:
 * The names of the commands are somewhat misleading. Here is clarification:
 *
 *  - a 'DMA' type command has a pointer to additional data and
 *    causes a DMA transfer to bring that into DMEM.
 *
 *  - an 'Immediate' type command isn't really 'immediate', in the
 *    traditional sense. This just means that the entire command fits
 *    in the 64-bit word, and the ucode can execute it 'immediately'
 *    without additional memory transfers.
 *
 *  - an 'RDP' command is identified as such because the RDP
 *    commands can be passed-thru the RSP and sent to the RDP
 *    directly. One further confusing thing, is that some 'DP'
 *    macros below actually generate immediate commands, not
 *    not direct DP commands.
 *
 * IMPLEMENTATION NOTE:
 * There is another group of RDP commands that includes the triangle commands
 * generated by the RSP code. These are the raw commands the rasterizer
 * hardware chews on, with slope info, etc. They will follow the RDP
 * ordering...
 *
 * IMPLEMENTATION NOTE:
 * The RDP hardware has some of these bit patterns wired up. If the hardware
 * changes, we must adjust this table, likewise we can't change/add things
 * once the hardware is frozen. (actually, the RDP hardware only looks at
 * the lower 6 bits of the command byte)
 *
 */

/* DMA commands: */
#define G_SPNOOP        0 /* handle 0 gracefully */
#define G_MTX           1
#define G_RESERVED0     2 /* not implemeted */
#define G_MOVEMEM       3 /* move a block of memory (up to 4 words) to dmem */
#define G_VTX           4
#define G_RESERVED1     5 /* not implemeted */
#define G_DL            6
#define G_COL           7 /* new in PD */
#define G_RESERVED3     8 /* not implemeted */
#define G_SPRITE2D_BASE 9 /* sprite command */

/* IMMEDIATE commands: */
#define G_IMMFIRST          -65
#define G_TRI1              (G_IMMFIRST-0)   /* -65 / 0xbf */
#define G_CULLDL            0                /* -66 / 0xbe */
#define G_POPMTX            0                /* -67 / 0xbd */
#define G_MOVEWORD          (G_IMMFIRST-3)   /* -68 / 0xbc */
#define G_TEXTURE           (G_IMMFIRST-4)   /* -69 / 0xbb */
#define G_SETOTHERMODE_H    (G_IMMFIRST-5)   /* -70 / 0xba */
#define G_SETOTHERMODE_L    (G_IMMFIRST-6)   /* -71 / 0xb9 */
#define G_ENDDL             (G_IMMFIRST-7)   /* -72 / 0xb8 */
#define G_SETGEOMETRYMODE   (G_IMMFIRST-8)   /* -73 / 0xb7 */
#define G_CLEARGEOMETRYMODE (G_IMMFIRST-9)   /* -74 / 0xb6 */
#define G_LINE3D            (G_IMMFIRST-10)  /* -75 / 0xb5 */
#define G_RDPHALF_1         (G_IMMFIRST-11)  /* -76 / 0xb4 */
#define G_RDPHALF_2         (G_IMMFIRST-12)  /* -77 / 0xb3 */
#define G_TRI4              (G_IMMFIRST-14)  /* -79 / 0xb1 */

/* RDP commands: */
#define G_NOOP            0xc0 /*   0 */

/* RDP commands: */
#define G_SETCIMG         0xff /* -1  */
#define G_SETZIMG         0xfe /* -2  */
#define G_SETTIMG         0xfd /* -3  */
#define G_SETCOMBINE      0xfc /* -4  */
#define G_SETENVCOLOR     0xfb /* -5  */
#define G_SETPRIMCOLOR    0xfa /* -6  */
#define G_SETBLENDCOLOR   0xf9 /* -7  */
#define G_SETFOGCOLOR     0xf8 /* -8  */
#define G_SETFILLCOLOR    0xf7 /* -9  */
#define G_FILLRECT        0xf6 /* -10 */
#define G_SETTILE         0xf5 /* -11 */
#define G_LOADTILE        0xf4 /* -12 */
#define G_LOADBLOCK       0xf3 /* -13 */
#define G_SETTILESIZE     0xf2 /* -14 */
#define G_LOADTLUT        0xf0 /* -16 */
#define G_RDPSETOTHERMODE 0xef /* -17 */
#define G_SETPRIMDEPTH    0xee /* -18 */
#define G_SETSCISSOR      0xed /* -19 */
#define G_SETCONVERT      0xec /* -20 */
#define G_SETKEYR         0xeb /* -21 */
#define G_SETKEYGB        0xea /* -22 */
#define G_RDPFULLSYNC     0xe9 /* -23 */
#define G_RDPTILESYNC     0xe8 /* -24 */
#define G_RDPPIPESYNC     0xe7 /* -25 */
#define G_RDPLOADSYNC     0xe6 /* -26 */
#define G_TEXRECTFLIP     0xe5 /* -27 */
#define G_TEXRECT         0xe4 /* -28 */

/*
 * Coordinate shift values, number of bits of fraction
 */
#define G_TEXTURE_IMAGE_FRAC 2

/*
 * G_MTX: parameter flags
 */
#define G_MTX_MODELVIEW  0x00 /* matrix types */
#define G_MTX_PROJECTION 0x01
#define G_MTX_MUL        0x00 /* concat or load */
#define G_MTX_LOAD       0x02
#define G_MTX_NOPUSH     0x00 /* push or not */
#define G_MTX_PUSH       0x04

/*
 * flags for G_SETGEOMETRYMODE
 * (this rendering state is maintained in RSP)
 *
 * DO NOT USE THE LOW 8 BITS OF GEOMETRYMODE:
 * The weird bit-ordering is for the micro-code: the lower byte
 * can be OR'd in with G_TRI_SHADE (11001100) to construct
 * the triangle command directly. Don't break it...
 *
 * DO NOT USE THE HIGH 8 BITS OF GEOMETRYMODE:
 * The high byte is OR'd with 0x703 to form the clip code mask.
 * If it is set to 0x04, this will cause near clipping to occur.
 * If it is zero, near clipping will not occur.
 *
 * Further explanation:
 * G_SHADE is necessary in order to see the color that you passed
 * down with the vertex. If G_SHADE isn't set, you need to set the DP
 * appropriately and use primcolor to see anything.
 *
 * G_SHADING_SMOOTH enabled means use all 3 colors of the triangle.
 * If it is not set, then do 'flat shading', where only one vertex color
 * is used (and all 3 vertices are set to that same color by the ucode)
 * See the man page for gSP1Triangle().
 *
 */
#define G_ZBUFFER            0x00000001
#define G_SHADE              0x00000004 /* enable Gouraud interp */
/* rest of low byte reserved for setup ucode */
#define G_TEXTURE_ENABLE     0x00000002 /* Microcode use only */
#define G_SHADING_SMOOTH     0x00000200 /* flat or smooth shaded */
#define G_CULL_FRONT         0x00001000
#define G_CULL_BACK          0x00002000
#define G_CULL_BOTH          0x00003000 /* To make code cleaner */
#define G_FOG                0x00010000
#define G_LIGHTING           0x00020000
#define G_TEXTURE_GEN        0x00040000
#define G_TEXTURE_GEN_LINEAR 0x00080000

/*
 * G_SETIMG fmt: set image formats
 */
#define G_IM_FMT_RGBA 0
#define G_IM_FMT_YUV  1
#define G_IM_FMT_CI   2
#define G_IM_FMT_IA   3
#define G_IM_FMT_I    4
#define G_IM_FMT_CUSTOMFONT    5

/*
 * G_SETIMG siz: set image pixel size
 */
#define G_IM_SIZ_4b  0
#define G_IM_SIZ_8b  1
#define G_IM_SIZ_16b 2
#define G_IM_SIZ_32b 3
#define G_IM_SIZ_DD  5

#define G_IM_SIZ_4b_BYTES       0
#define G_IM_SIZ_4b_TILE_BYTES  G_IM_SIZ_4b_BYTES
#define G_IM_SIZ_4b_LINE_BYTES  G_IM_SIZ_4b_BYTES

#define G_IM_SIZ_8b_BYTES       1
#define G_IM_SIZ_8b_TILE_BYTES  G_IM_SIZ_8b_BYTES
#define G_IM_SIZ_8b_LINE_BYTES  G_IM_SIZ_8b_BYTES

#define G_IM_SIZ_16b_BYTES      2
#define G_IM_SIZ_16b_TILE_BYTES G_IM_SIZ_16b_BYTES
#define G_IM_SIZ_16b_LINE_BYTES G_IM_SIZ_16b_BYTES

#define G_IM_SIZ_32b_BYTES      4
#define G_IM_SIZ_32b_TILE_BYTES 2
#define G_IM_SIZ_32b_LINE_BYTES 2

#define G_IM_SIZ_4b_LOAD_BLOCK  G_IM_SIZ_16b
#define G_IM_SIZ_8b_LOAD_BLOCK  G_IM_SIZ_16b
#define G_IM_SIZ_16b_LOAD_BLOCK G_IM_SIZ_16b
#define G_IM_SIZ_32b_LOAD_BLOCK G_IM_SIZ_32b

#define G_IM_SIZ_4b_SHIFT  2
#define G_IM_SIZ_8b_SHIFT  1
#define G_IM_SIZ_16b_SHIFT 0
#define G_IM_SIZ_32b_SHIFT 0

#define G_IM_SIZ_4b_INCR  3
#define G_IM_SIZ_8b_INCR  1
#define G_IM_SIZ_16b_INCR 0
#define G_IM_SIZ_32b_INCR 0

/*
 * G_SETCOMBINE: color combine modes
 */
/* Color combiner constants: */
#define G_CCMUX_COMBINED        0
#define G_CCMUX_TEXEL0          1
#define G_CCMUX_TEXEL1          2
#define G_CCMUX_PRIMITIVE       3
#define G_CCMUX_SHADE           4
#define G_CCMUX_ENVIRONMENT     5
#define G_CCMUX_CENTER          6
#define G_CCMUX_SCALE           6
#define G_CCMUX_COMBINED_ALPHA  7
#define G_CCMUX_TEXEL0_ALPHA    8
#define G_CCMUX_TEXEL1_ALPHA    9
#define G_CCMUX_PRIMITIVE_ALPHA 10
#define G_CCMUX_SHADE_ALPHA     11
#define G_CCMUX_ENV_ALPHA       12
#define G_CCMUX_LOD_FRACTION    13
#define G_CCMUX_PRIM_LOD_FRAC   14
#define G_CCMUX_NOISE           7
#define G_CCMUX_K4              7
#define G_CCMUX_K5              15
#define G_CCMUX_1               6
#define G_CCMUX_0               31

/* Alpha combiner constants: */
#define G_ACMUX_COMBINED      0
#define G_ACMUX_TEXEL0        1
#define G_ACMUX_TEXEL1        2
#define G_ACMUX_PRIMITIVE     3
#define G_ACMUX_SHADE         4
#define G_ACMUX_ENVIRONMENT   5
#define G_ACMUX_LOD_FRACTION  0
#define G_ACMUX_PRIM_LOD_FRAC 6
#define G_ACMUX_1             6
#define G_ACMUX_0             7

/* typical CC cycle 1 modes */
#define G_CC_MODULATEI              TEXEL0,                   0,           SHADE,        0,           0,         0,     0,         SHADE
#define G_CC_MODULATEIA             TEXEL0,                   0,           SHADE,        0,           TEXEL0,    0,     SHADE,     0
#define G_CC_MODULATEIDECALA        TEXEL0,                   0,           SHADE,        0,           0,         0,     0,         TEXEL0
#define G_CC_MODULATERGB            G_CC_MODULATEI
#define G_CC_MODULATERGBDECALA      G_CC_MODULATEIDECALA
#define G_CC_MODULATEI_PRIM         TEXEL0,                   0,           PRIMITIVE,    0,           0,         0,     0,         PRIMITIVE
#define G_CC_MODULATEIA_PRIM        TEXEL0,                   0,           PRIMITIVE,    0,           TEXEL0,    0,     PRIMITIVE, 0
#define G_CC_MODULATEIDECALA_PRIM   TEXEL0,                   0,           PRIMITIVE,    0,           0,         0,     0,         TEXEL0
#define G_CC_MODULATERGB_PRIM       G_CC_MODULATEI_PRIM
#define G_CC_MODULATERGBA_PRIM      G_CC_MODULATEIA_PRIM
#define G_CC_MODULATERGBDECALA_PRIM G_CC_MODULATEIDECALA_PRIM
#define G_CC_DECALRGB               0,                        0,           0,            TEXEL0,      0,         0,     0,         SHADE
#define G_CC_DECALRGBA              0,                        0,           0,            TEXEL0,      0,         0,     0,         TEXEL0
#define G_CC_BLENDI                 ENVIRONMENT,              SHADE,       TEXEL0,       SHADE,       0,         0,     0,         SHADE
#define G_CC_BLENDIA                ENVIRONMENT,              SHADE,       TEXEL0,       SHADE,       TEXEL0,    0,     SHADE,     0
#define G_CC_BLENDIDECALA           ENVIRONMENT,              SHADE,       TEXEL0,       SHADE,       0,         0,     0,         TEXEL0
#define G_CC_BLENDRGBA              TEXEL0,                   SHADE,       TEXEL0_ALPHA, SHADE,       0,         0,     0,         SHADE
#define G_CC_BLENDRGBDECALA         TEXEL0,                   SHADE,       TEXEL0_ALPHA, SHADE,       0,         0,     0,         TEXEL0
#define G_CC_ADDRGB                 1,                        0,           TEXEL0,       SHADE,       0,         0,     0,         SHADE
#define G_CC_ADDRGBDECALA           1,                        0,           TEXEL0,       SHADE,       0,         0,     0,         TEXEL0

/* used for 1-cycle sparse mip-maps, primitive color has color of lowest LOD */
#define _G_CC_SPARSEST      PRIMITIVE,   TEXEL0,    LOD_FRACTION,  TEXEL0,    PRIMITIVE, TEXEL0, LOD_FRACTION,  TEXEL0
#define G_CC_TEMPLERP       TEXEL1,      TEXEL0,    PRIM_LOD_FRAC, TEXEL0,    TEXEL1,    TEXEL0, PRIM_LOD_FRAC, TEXEL0

/* typical CC cycle 1 modes, usually followed by other cycle 2 modes */
#define G_CC_TRILERP        TEXEL1,      TEXEL0,    LOD_FRACTION,  TEXEL0,    TEXEL1,    TEXEL0, LOD_FRACTION,  TEXEL0
#define G_CC_INTERFERENCE   TEXEL0,      0,         TEXEL1,        0,         TEXEL0,    0,      TEXEL1,        0

/* typical CC cycle 2 modes */
#define G_CC_MODULATEIA2        COMBINED,             0,        SHADE,     0,        COMBINED,    0,        SHADE,     0

/*
 * G_SETOTHERMODE_L sft: shift count
 */
#define G_MDSFT_ALPHACOMPARE 0
#define G_MDSFT_ZSRCSEL      2
#define G_MDSFT_RENDERMODE   3
#define G_MDSFT_BLENDER      16

/*
 * G_SETOTHERMODE_H sft: shift count
 */
#define G_MDSFT_BLENDMASK   0 /* unsupported */
#define G_MDSFT_ALPHADITHER 4
#define G_MDSFT_RGBDITHER   6

#define G_MDSFT_COMBKEY     8
#define G_MDSFT_TEXTCONV    9
#define G_MDSFT_TEXTFILT    12
#define G_MDSFT_TEXTLUT     14
#define G_MDSFT_TEXTLOD     16
#define G_MDSFT_TEXTDETAIL  17
#define G_MDSFT_TEXTPERSP   19
#define G_MDSFT_CYCLETYPE   20
#define G_MDSFT_COLORDITHER 22 /* unsupported in HW 2.0 */
#define G_MDSFT_PIPELINE    23

/* G_SETOTHERMODE_H gPipelineMode */
#define G_PM_1PRIMITIVE (1 << G_MDSFT_PIPELINE)

/* G_SETOTHERMODE_H gSetCycleType */
#define G_CYC_1CYCLE    (0 << G_MDSFT_CYCLETYPE)
#define G_CYC_2CYCLE    (1 << G_MDSFT_CYCLETYPE)
#define G_CYC_COPY      (2 << G_MDSFT_CYCLETYPE)
#define G_CYC_FILL      (3 << G_MDSFT_CYCLETYPE)

/* G_SETOTHERMODE_H gSetTexturePersp */
#define G_TP_NONE       (0 << G_MDSFT_TEXTPERSP)
#define G_TP_PERSP      (1 << G_MDSFT_TEXTPERSP)

/* G_SETOTHERMODE_H gSetTextureDetail */
#define G_TD_CLAMP      (0 << G_MDSFT_TEXTDETAIL)
#define G_TD_SHARPEN    (1 << G_MDSFT_TEXTDETAIL)
#define G_TD_DETAIL     (2 << G_MDSFT_TEXTDETAIL)

/* G_SETOTHERMODE_H gSetTextureLOD */
#define G_TL_TILE       (0 << G_MDSFT_TEXTLOD)
#define G_TL_LOD        (1 << G_MDSFT_TEXTLOD)

/* G_SETOTHERMODE_H gSetTextureLUT */
#define G_TT_NONE       (0 << G_MDSFT_TEXTLUT)
#define G_TT_RGBA16     (2 << G_MDSFT_TEXTLUT)
#define G_TT_IA16       (3 << G_MDSFT_TEXTLUT)

/* G_SETOTHERMODE_H gSetTextureFilter */
#define G_TF_POINT      (0 << G_MDSFT_TEXTFILT)
#define G_TF_AVERAGE    (3 << G_MDSFT_TEXTFILT)
#define G_TF_BILERP     (2 << G_MDSFT_TEXTFILT)

/* G_SETOTHERMODE_H gSetTextureConvert */
#define G_TC_FILT       (6 << G_MDSFT_TEXTCONV)

/* G_SETOTHERMODE_H gSetCombineKey */
#define G_CK_NONE       (0 << G_MDSFT_COMBKEY)

/* G_SETOTHERMODE_H gSetAlphaDither */
#define G_AD_PATTERN    (0 << G_MDSFT_ALPHADITHER)
#define G_AD_NOTPATTERN (1 << G_MDSFT_ALPHADITHER)
#define G_AD_NOISE      (2 << G_MDSFT_ALPHADITHER)
#define G_AD_DISABLE    (3 << G_MDSFT_ALPHADITHER)

/* G_SETOTHERMODE_L gSetAlphaCompare */
#define G_AC_NONE       (0 << G_MDSFT_ALPHACOMPARE)
#define G_AC_THRESHOLD  (1 << G_MDSFT_ALPHACOMPARE)
#define G_AC_DITHER     (3 << G_MDSFT_ALPHACOMPARE)

/* G_SETOTHERMODE_L gSetDepthSource */
#define G_ZS_PIXEL      (0 << G_MDSFT_ZSRCSEL)
#define G_ZS_PRIM       (1 << G_MDSFT_ZSRCSEL)

/* G_SETOTHERMODE_L gSetRenderMode */
#define AA_EN         0x8
#define Z_CMP         0x10
#define Z_UPD         0x20
#define IM_RD         0x40
#define CLR_ON_CVG    0x80
#define CVG_DST_CLAMP 0
#define CVG_DST_WRAP  0x100
#define CVG_DST_FULL  0x200
#define CVG_DST_SAVE  0x300
#define ZMODE_OPA     0
#define ZMODE_INTER   0x400
#define ZMODE_XLU     0x800
#define ZMODE_DEC     0xc00
#define CVG_X_ALPHA   0x1000
#define ALPHA_CVG_SEL 0x2000
#define FORCE_BL      0x4000
#define TEX_EDGE      0x0000 /* used to be 0x8000 */

#define G_BL_CLR_IN  0
#define G_BL_CLR_MEM 1
#define G_BL_CLR_BL  2
#define G_BL_CLR_FOG 3
#define G_BL_1MA     0
#define G_BL_A_MEM   1
#define G_BL_A_IN    0
#define G_BL_A_FOG   1
#define G_BL_A_SHADE 2
#define G_BL_1       2
#define G_BL_0       3

#define GBL_c1(m1a, m1b, m2a, m2b)                        \
    (uint32_t)(m1a) << 30 | (uint32_t)(m1b) << 26 | (uint32_t)(m2a) << 22 | (uint32_t)(m2b) << 18

#define GBL_c2(m1a, m1b, m2a, m2b)                        \
    (uint32_t)(m1a) << 28 | (uint32_t)(m1b) << 24 | (uint32_t)(m2a) << 20 | (uint32_t)(m2b) << 16

#define RM_AA_ZB_OPA_SURF(clk)                                   \
    AA_EN | Z_CMP | Z_UPD | IM_RD | CVG_DST_CLAMP |              \
    ZMODE_OPA | ALPHA_CVG_SEL |                                  \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM)

#define RM_AA_ZB_XLU_SURF(clk)                                 \
    AA_EN | Z_CMP | IM_RD | CVG_DST_WRAP | CLR_ON_CVG |        \
    FORCE_BL | ZMODE_XLU |                                     \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA)

#define RM_AA_ZB_OPA_DECAL(clk)                                  \
    AA_EN | Z_CMP | IM_RD | CVG_DST_WRAP | ALPHA_CVG_SEL |       \
    ZMODE_DEC |                                                  \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM)

#define RM_AA_ZB_XLU_DECAL(clk)                                \
    AA_EN | Z_CMP | IM_RD | CVG_DST_WRAP | CLR_ON_CVG |        \
    FORCE_BL | ZMODE_DEC |                                     \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA)

#define RM_AA_ZB_XLU_LINE(clk)                                 \
    AA_EN | Z_CMP | IM_RD | CVG_DST_CLAMP | CVG_X_ALPHA |      \
    ALPHA_CVG_SEL | FORCE_BL | ZMODE_XLU |                     \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA)

#define RM_AA_ZB_DEC_LINE(clk)                                 \
    AA_EN | Z_CMP | IM_RD | CVG_DST_SAVE | CVG_X_ALPHA |       \
    ALPHA_CVG_SEL | FORCE_BL | ZMODE_DEC |                     \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA)

#define RM_AA_ZB_TEX_EDGE(clk)                                   \
    AA_EN | Z_CMP | Z_UPD | IM_RD | CVG_DST_CLAMP |              \
    CVG_X_ALPHA | ALPHA_CVG_SEL | ZMODE_OPA | TEX_EDGE |         \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM)

#define RM_AA_ZB_TEX_INTER(clk)                                  \
    AA_EN | Z_CMP | Z_UPD | IM_RD | CVG_DST_CLAMP |              \
    CVG_X_ALPHA | ALPHA_CVG_SEL | ZMODE_INTER | TEX_EDGE |       \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM)

#define RM_AA_ZB_SUB_SURF(clk)                                   \
    AA_EN | Z_CMP | Z_UPD | IM_RD | CVG_DST_FULL |               \
    ZMODE_OPA | ALPHA_CVG_SEL |                                  \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM)

#define RM_AA_ZB_OPA_TERR(clk)                                 \
    AA_EN | Z_CMP | Z_UPD | IM_RD | CVG_DST_CLAMP |            \
    ZMODE_OPA | ALPHA_CVG_SEL |                                \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA)

#define RM_AA_OPA_SURF(clk)                                      \
    AA_EN | IM_RD | CVG_DST_CLAMP |                              \
    ZMODE_OPA | ALPHA_CVG_SEL |                                  \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM)

#define RM_RA_OPA_SURF(clk)                                      \
    AA_EN | CVG_DST_CLAMP |                                      \
    ZMODE_OPA | ALPHA_CVG_SEL |                                  \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM)

#define RM_AA_XLU_SURF(clk)                                    \
    AA_EN | IM_RD | CVG_DST_WRAP | CLR_ON_CVG | FORCE_BL |     \
    ZMODE_OPA |                                                \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA)

#define RM_AA_TEX_EDGE(clk)                                      \
    AA_EN | IM_RD | CVG_DST_CLAMP |                              \
    CVG_X_ALPHA | ALPHA_CVG_SEL | ZMODE_OPA | TEX_EDGE |         \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM)

#define RM_AA_OPA_TERR(clk)                                    \
    AA_EN | IM_RD | CVG_DST_CLAMP |                            \
    ZMODE_OPA | ALPHA_CVG_SEL |                                \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA)

#define RM_ZB_OPA_SURF(clk)                                      \
    Z_CMP | Z_UPD | CVG_DST_FULL | ALPHA_CVG_SEL |               \
    ZMODE_OPA |                                                  \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM)

#define RM_ZB_XLU_SURF(clk)                                    \
    Z_CMP | IM_RD | CVG_DST_FULL | FORCE_BL | ZMODE_XLU |      \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA)

#define RM_ZB_OPA_DECAL(clk)                                     \
    Z_CMP | CVG_DST_FULL | ALPHA_CVG_SEL | ZMODE_DEC |           \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM)

#define RM_ZB_XLU_DECAL(clk)                                   \
    Z_CMP | IM_RD | CVG_DST_FULL | FORCE_BL | ZMODE_DEC |      \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA)

#define RM_ZB_CLD_SURF(clk)                                    \
    Z_CMP | IM_RD | CVG_DST_SAVE | FORCE_BL | ZMODE_XLU |      \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA)

#define RM_ZB_OVL_SURF(clk)                                    \
    Z_CMP | IM_RD | CVG_DST_SAVE | FORCE_BL | ZMODE_DEC |      \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA)

#define RM_ZB_PCL_SURF(clk)                              \
    Z_CMP | Z_UPD | CVG_DST_FULL | ZMODE_OPA |           \
    G_AC_DITHER |                                        \
    GBL_c##clk(G_BL_CLR_IN, G_BL_0, G_BL_CLR_IN, G_BL_1)


#define RM_OPA_SURF(clk)                                 \
    CVG_DST_CLAMP | FORCE_BL | ZMODE_OPA |               \
    GBL_c##clk(G_BL_CLR_IN, G_BL_0, G_BL_CLR_IN, G_BL_1)

#define RM_XLU_SURF(clk)                                       \
    IM_RD | CVG_DST_FULL | FORCE_BL | ZMODE_OPA |              \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA)

#define RM_CLD_SURF(clk)                                       \
    IM_RD | CVG_DST_SAVE | FORCE_BL | ZMODE_OPA |              \
    GBL_c##clk(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA)

#define RM_NOOP(clk)       \
    GBL_c##clk(0, 0, 0, 0)

#define G_RM_AA_ZB_OPA_SURF   RM_AA_ZB_OPA_SURF(1)
#define G_RM_AA_ZB_OPA_SURF2  RM_AA_ZB_OPA_SURF(2)
#define G_RM_AA_ZB_XLU_SURF   RM_AA_ZB_XLU_SURF(1)
#define G_RM_AA_ZB_XLU_SURF2  RM_AA_ZB_XLU_SURF(2)
#define G_RM_AA_ZB_OPA_DECAL  RM_AA_ZB_OPA_DECAL(1)
#define G_RM_AA_ZB_OPA_DECAL2 RM_AA_ZB_OPA_DECAL(2)
#define G_RM_AA_ZB_XLU_DECAL  RM_AA_ZB_XLU_DECAL(1)
#define G_RM_AA_ZB_XLU_DECAL2 RM_AA_ZB_XLU_DECAL(2)
#define G_RM_AA_ZB_XLU_LINE   RM_AA_ZB_XLU_LINE(1)
#define G_RM_AA_ZB_XLU_LINE2  RM_AA_ZB_XLU_LINE(2)
#define G_RM_AA_ZB_DEC_LINE   RM_AA_ZB_DEC_LINE(1)
#define G_RM_AA_ZB_DEC_LINE2  RM_AA_ZB_DEC_LINE(2)
#define G_RM_AA_ZB_TEX_EDGE   RM_AA_ZB_TEX_EDGE(1)
#define G_RM_AA_ZB_TEX_EDGE2  RM_AA_ZB_TEX_EDGE(2)
#define G_RM_AA_ZB_TEX_INTER  RM_AA_ZB_TEX_INTER(1)
#define G_RM_AA_ZB_TEX_INTER2 RM_AA_ZB_TEX_INTER(2)
#define G_RM_AA_ZB_SUB_SURF   RM_AA_ZB_SUB_SURF(1)
#define G_RM_AA_ZB_OPA_TERR2  RM_AA_ZB_OPA_TERR(2)

#define G_RM_AA_OPA_SURF      RM_AA_OPA_SURF(1)
#define G_RM_AA_OPA_SURF2     RM_AA_OPA_SURF(2)
#define G_RM_AA_XLU_SURF      RM_AA_XLU_SURF(1)
#define G_RM_AA_XLU_SURF2     RM_AA_XLU_SURF(2)
#define G_RM_AA_TEX_EDGE      RM_AA_TEX_EDGE(1)
#define G_RM_AA_TEX_EDGE2     RM_AA_TEX_EDGE(2)
#define G_RM_AA_OPA_TERR      RM_AA_OPA_TERR(1)
#define G_RM_AA_OPA_TERR2     RM_AA_OPA_TERR(2)

#define G_RM_RA_OPA_SURF      RM_RA_OPA_SURF(1)
#define G_RM_RA_OPA_SURF2     RM_RA_OPA_SURF(2)

#define G_RM_ZB_OPA_SURF      RM_ZB_OPA_SURF(1)
#define G_RM_ZB_OPA_SURF2     RM_ZB_OPA_SURF(2)
#define G_RM_ZB_XLU_SURF      RM_ZB_XLU_SURF(1)
#define G_RM_ZB_XLU_SURF2     RM_ZB_XLU_SURF(2)
#define G_RM_ZB_CLD_SURF      RM_ZB_CLD_SURF(1)
#define G_RM_ZB_CLD_SURF2     RM_ZB_CLD_SURF(2)
#define G_RM_ZB_OVL_SURF      RM_ZB_OVL_SURF(1)
#define G_RM_ZB_OVL_SURF2     RM_ZB_OVL_SURF(2)
#define G_RM_ZB_PCL_SURF      RM_ZB_PCL_SURF(1)
#define G_RM_ZB_PCL_SURF2     RM_ZB_PCL_SURF(2)

#define G_RM_OPA_SURF         RM_OPA_SURF(1)
#define G_RM_OPA_SURF2        RM_OPA_SURF(2)
#define G_RM_XLU_SURF         RM_XLU_SURF(1)
#define G_RM_XLU_SURF2        RM_XLU_SURF(2)
#define G_RM_CLD_SURF         RM_CLD_SURF(1)
#define G_RM_CLD_SURF2        RM_CLD_SURF(2)
#define G_RM_NOOP             RM_NOOP(1)
#define G_RM_NOOP2            RM_NOOP(2)

#define G_RM_FOG_SHADE_A GBL_c1(G_BL_CLR_FOG, G_BL_A_SHADE, G_BL_CLR_IN, G_BL_1MA)
#define G_RM_FOG_PRIM_A  GBL_c1(G_BL_CLR_FOG, G_BL_A_FOG,   G_BL_CLR_IN, G_BL_1MA)
#define G_RM_PASS        GBL_c1(G_BL_CLR_IN,  G_BL_0,       G_BL_CLR_IN, G_BL_1)

/* flags to inhibit pushing of the display list (on branch) */
#define G_DL_PUSH   0x00
#define G_DL_NOPUSH 0x01

typedef struct {
	union {
		struct {
			/*0x00*/ int16_t x;
			/*0x02*/ int16_t y;
			/*0x04*/ int16_t z;
		};
		int16_t v[3];
	};
	/*0x06*/ uint8_t flags;
	/*0x07*/ uint8_t colour;
	/*0x08*/ int16_t s;
	/*0x0a*/ int16_t t;
} Vtx;

typedef union {
    uint32_t word;
    uint8_t bytes[4];
    struct {
        uint8_t r;
        uint8_t g;
        uint8_t b;
        uint8_t a;
    };
} Col;

/*
 * Triangle face
 */
typedef struct {
	unsigned char v[3]; // reverse order
	unsigned char flag;
} Tri;

#define GFX_TRI_VTX(i) (2 - i)

typedef float Mtx[4][4];

typedef struct {
	int vscale[2];
	int vtrans[2];
} Vp_t;

typedef union {
	Vp_t          vp;
} Vp;

/*
 * MOVEMEM indices
 *
 * Each of these indexes an entry in a dmem table
 * which points to a 1-4 word block of dmem in
 * which to store a 1-4 word DMA.
 *
 */
#define G_MV_VIEWPORT 0x80
#define G_MV_LOOKATY  0x82
#define G_MV_LOOKATX  0x84
#define G_MV_L0       0x86
#define G_MV_L1       0x88
#define G_MV_L2       0x8a

/*
 * MOVEWORD indices
 *
 * Each of these indexes an entry in a dmem table
 * which points to a word in dmem in dmem where
 * an immediate word will be stored.
 *
 */
#define G_MW_MATRIX    0x00 /* NOTE: also used by movemem */
#define G_MW_NUMLIGHT  0x02
#define G_MW_CLIP      0x04
#define G_MW_SEGMENT   0x06
#define G_MW_FOG       0x08

/*
 * These are offsets from the address in the dmem table
 */
#define G_MWO_NUMLIGHT       0x00
#define G_MWO_CLIP_RNX       0x04
#define G_MWO_CLIP_RNY       0x0c
#define G_MWO_CLIP_RPX       0x14
#define G_MWO_CLIP_RPY       0x1c
#define G_MWO_FOG            0x00
#define G_MWO_POINT_ST       0x14

/*
 * Light structure.
 *
 * Note: only directional (infinite) lights are currently supported.
 *
 * Note: the weird order is for the DMEM alignment benefit of
 * the microcode.
 *
 */

typedef struct {
	unsigned char col[3];  /* diffuse light value (rgba) */
	char          pad1;
	unsigned char colc[3]; /* copy of diffuse light value (rgba) */
	char          pad2;
	signed char   dir[3];  /* direction of light (normalized) */
	char          pad3;
} Light_t;

typedef struct {
	unsigned char col[3];  /* ambient light value (rgba) */
	char          pad1;
	unsigned char colc[3]; /* copy of ambient light value (rgba) */
	char          pad2;
} Ambient_t;

typedef union {
	Light_t       l;
	long long int force_structure_alignment[2];
} Light;

typedef union {
	Ambient_t     l;
	long long int force_structure_alignment[1];
} Ambient;

typedef struct {
	Ambient a;
	Light   l[1];
} Lights1;

typedef struct {
	Light l[2];
} LookAt;

#define gdSPDefLights1(ar,ag,ab,r1,g1,b1,x1,y1,z1) \
{                                                  \
    {{ {ar,ag,ab},0,{ar,ag,ab},0}},                \
    {{{ {r1,g1,b1},0,{r1,g1,b1},0,{x1,y1,z1},0}}}  \
}

/*
 *  Graphics DMA Packet
 */
#ifdef PLATFORM_64BIT
typedef struct {
    intptr_t par : 24;
    intptr_t cmd : 8;
    intptr_t len : 32;
    uintptr_t addr;
} Gdma;
#else
typedef struct {
	int len:16;
	int par:8;
	int cmd:8;
	unsigned int addr;
} Gdma;
#endif

/*
 * Graphics Immediate Mode Packet types
 */
typedef struct {
    int pad:24;
    int cmd:8;
	Tri tri;
} Gtri;

typedef struct {
	unsigned char z1:4;
	unsigned char z2:4;
	unsigned char z3:4;
	unsigned char z4:4;
	unsigned char pad:8;
	unsigned char cmd:8;
#ifdef PLATFORM_64BIT
    unsigned char pad2[4];
#endif
	unsigned char x1:4;
	unsigned char y1:4;
	unsigned char x2:4;
	unsigned char y2:4;
	unsigned char x3:4;
	unsigned char y3:4;
	unsigned char x4:4;
	unsigned char y4:4;
#ifdef PLATFORM_64BIT
    unsigned char pad3[4];
#endif
} Gtri4;

typedef struct {
	int           cmd:8;
	int           pad1:24;
	int           pad2:24;
	unsigned char param:8;
} Gpopmtx;

typedef struct {
	int cmd:8;
	int pad0:8;
	int mw_index:8;
	int number:8;
	int pad1:8;
	int base:24;
} Gsegment;

typedef struct {
	unsigned char  on;
	unsigned char  tile;
	unsigned char  lodscale;
	unsigned char  cmd;
	unsigned short t;
	unsigned short s;
} Gtexture;

/*
 * Textured rectangles are 128 bits not 64 bits
 */
typedef struct {
	unsigned long w0;
	unsigned long w1;
	unsigned long w2;
	unsigned long w3;
} TexRect;

/*
 * Generic Gfx Packet
 */
typedef struct {
	uintptr_t w0;
	uintptr_t w1;
} Gwords;

typedef struct {
	unsigned int subcmd:3;
} GunkC0;

typedef struct {
	unsigned int unk10:16;
	unsigned int unk0c:4;
	unsigned int unk08:4;
	unsigned int cmd:8;
	unsigned int offset:24;
	unsigned int seg:8;
} Gvtx;

/*
 * This union is the fundamental type of the display list.
 * It is, by law, exactly 64 bits in size.
 */
typedef union {
	Gwords         words;
#ifdef PLATFORM_64BIT
	uint8_t             bytes[16];
#else
	uint8_t             bytes[8];
#endif
	Gdma           dma;
	Gvtx           vtx;
	Gtri           tri;
	Gtri4          tri4;
	Gtexture       texture;
	GunkC0         unkc0;
#ifdef PLATFORM_64BIT
	long long int  force_structure_alignment[2];
#else
	long long int  force_structure_alignment;
#endif
} Gfx;

#ifdef PLATFORM_64BIT
#define GFX_W0_BYTE(i) (3 - (i))
#define GFX_W1_BYTE(i) (11 - (i))
#else
#define GFX_W0_BYTE(i) (3 - (i))
#define GFX_W1_BYTE(i) (7 - (i))
#endif

/*
 * Macros to assemble the graphics display list
 */

/*
 * DMA macros
 */

#define gDma1p(pkt, c, s, l, p)                                 \
{                                                               \
    Gfx *_g = (Gfx *)(pkt);                                     \
                                                                \
    _g->words.w0 = (_SHIFTL((c), 24, 8) | _SHIFTL((p), 16, 8) | \
            _SHIFTL((l), 0, 16));                               \
    _g->words.w1 = (uintptr_t)(s);                              \
}

#define gSPDisplayList(pkt,dl)  gDma1p(pkt,G_DL,dl,0,G_DL_PUSH)

/*
 * RSP short command (no DMA required) macros
 */


#define gImmp1(pkt, c, p0)              \
{                                       \
    Gfx *_g = (Gfx *)(pkt);             \
                                        \
    _g->words.w0 = _SHIFTL((c), 24, 8); \
    _g->words.w1 = (uintptr_t)(p0);     \
}

#define gImmp21(pkt, c, p0, p1, dat)                              \
{                                                                 \
    Gfx *_g = (Gfx *)(pkt);                                       \
                                                                  \
    _g->words.w0 = (_SHIFTL((c), 24, 8)  | _SHIFTL((p0), 8, 16) | \
            _SHIFTL((p1), 0, 8));                                 \
    _g->words.w1 = (uintptr_t) (dat);                             \
}

#define gMoveWd(pkt, index, offset, data)           \
    gImmp21((pkt), G_MOVEWORD, offset, index, data)

// we mark all segmented addresses so that it'll be easier to recognize them later
#define SEGADDR(x) ((void *)((uintptr_t)(x) | 1))
#define UNSEGADDR(x) ((uintptr_t)(x) & ~1)

/*
 * Lighting Macros
 */
#define NUML(n)     (((n)+1)*32 + 0x80000000)

#define gSPNumLights(pkt, n)                             \
    gMoveWd(pkt, G_MW_NUMLIGHT, G_MWO_NUMLIGHT, NUML(n))

#define gSPLight(pkt, l, n)                                    \
    gDma1p(pkt, G_MOVEMEM, l, sizeof(Light),((n)-1)*2+G_MV_L0)

#define gSPSetLights1(pkt,name)    \
{                                  \
    gSPNumLights(pkt,1); \
    gSPLight(pkt,&name.l[0],1);    \
    gSPLight(pkt,&name.a,2);       \
}

#define gsSPEndDisplayList()   \
{                              \
    _SHIFTL(G_ENDDL, 24, 8), 0 \
}

/* Fraction never used in fill */
#define gDPFillRectangle(pkt, ulx, uly, lrx, lry)                    \
{                                                                    \
    Gfx *_g = (Gfx *)(pkt);                                          \
                                                                     \
    _g->words.w0 = (_SHIFTL(G_FILLRECT, 24, 8) |                     \
            _SHIFTL((lrx), 14, 10) | _SHIFTL((lry), 2, 10));         \
    _g->words.w1 = (_SHIFTL((ulx), 14, 10) | _SHIFTL((uly), 2, 10)); \
}

#define gSetImage(pkt, cmd, fmt, siz, width, i)                \
{                                                              \
    Gfx *_g = (Gfx *)(pkt);                                    \
                                                               \
    _g->words.w0 = _SHIFTL(cmd, 24, 8) | _SHIFTL(fmt, 21, 3) | \
    _SHIFTL(siz, 19, 2) | _SHIFTL((width)-1, 0, 12);           \
    _g->words.w1 = (uintptr_t)(i);                             \
}

#define gsSetImage(cmd, fmt, siz, width, i)          \
{                                                    \
    _SHIFTL(cmd, 24, 8) | _SHIFTL(fmt, 21, 3) |      \
    _SHIFTL(siz, 19, 2) | _SHIFTL((width)-1, 0, 12), \
    (uintptr_t)(i)                                   \
}

#define gDPSetTextureImage(pkt, f, s, w, i) gSetImage(pkt, G_SETTIMG, f, s, w, i)
#define gsDPSetTextureImage(f, s, w, i)     gsSetImage(G_SETTIMG, f, s, w, i)

/*
 * RDP macros
 */

#define GCCc0w0(saRGB0, mRGB0, saA0, mA0)                 \
    (_SHIFTL((saRGB0), 20, 4) | _SHIFTL((mRGB0), 15, 5) | \
     _SHIFTL((saA0), 12, 3) | _SHIFTL((mA0), 9, 3))

#define GCCc1w0(saRGB1, mRGB1)                         \
    (_SHIFTL((saRGB1), 5, 4) | _SHIFTL((mRGB1), 0, 5))

#define GCCc0w1(sbRGB0, aRGB0, sbA0, aA0)                 \
    (_SHIFTL((sbRGB0), 28, 4) | _SHIFTL((aRGB0), 15, 3) | \
     _SHIFTL((sbA0), 12, 3) | _SHIFTL((aA0), 9, 3))

#define GCCc1w1(sbRGB1, saA1, mA1, aRGB1, sbA1, aA1)     \
    (_SHIFTL((sbRGB1), 24, 4) | _SHIFTL((saA1), 21, 3) | \
     _SHIFTL((mA1), 18, 3) | _SHIFTL((aRGB1), 6, 3) |    \
     _SHIFTL((sbA1), 3, 3) | _SHIFTL((aA1), 0, 3))

/*
 * Texturing macros
 */

/* These are also defined defined above for Sprite Microcode */

#define G_TX_LOADTILE   7
#define G_TX_RENDERTILE 0
#define G_TX_NOMIRROR   0
#define G_TX_WRAP       0
#define G_TX_MIRROR     0x1
#define G_TX_CLAMP      0x2
#define G_TX_NOMASK     0
#define G_TX_NOLOD      0


#ifndef MAX
#define MAX(a, b) ((a) > (b) ? (a) : (b))
#endif

#ifndef MIN
#define MIN(a, b) ((a) < (b) ? (a) : (b))
#endif
/*
 *  Dxt is the inverse of the number of 64-bit words in a line of
 *  the texture being loaded using the load_block command.  If
 *  there are any 1's to the right of the 11th fractional bit,
 *  dxt should be rounded up.  The following macros accomplish
 *  this.  The 4b macros are a special case since 4-bit textures
 *  are loaded as 8-bit textures.  Dxt is fixed point 1.11. RJM
 */
#define G_TX_DXT_FRAC 11

/*
 *  For RCP 2.0, the maximum number of texels that can be loaded
 *  using a load_block command is 2048.  In order to load the total
 *  4kB of Tmem, change the texel size when loading to be G_IM_SIZ_16b,
 *  then change the tile to the proper texel size after the load.
 *  The g*DPLoadTextureBlock macros already do this, so this change
 *  will be transparent if you use these macros.  If you use
 *  the g*DPLoadBlock macros directly, you will need to handle this
 *  tile manipulation yourself.  RJM.
 */
#define G_TX_LDBLK_MAX_TXL 2047

#define TXL2WORDS(txls, b_txl) MAX(1, ((txls)*(b_txl)/8))

#define CALC_DXT(width, b_txl)                              \
    (((1 << G_TX_DXT_FRAC) + TXL2WORDS(width, b_txl) - 1) / \
     TXL2WORDS(width, b_txl))

#define gDPLoadTileGeneric(pkt, c, tile, uls, ult, lrs, lrt)     \
{                                                                \
    Gfx *_g = (Gfx *)(pkt);                                      \
                                                                 \
    _g->words.w0 = _SHIFTL(c, 24, 8) | _SHIFTL(uls, 12, 12) |    \
    _SHIFTL(ult, 0, 12);                                         \
    _g->words.w1 = _SHIFTL(tile, 24, 3) | _SHIFTL(lrs, 12, 12) | \
    _SHIFTL(lrt, 0, 12);                                         \
}

#define gDPSetTileSize(pkt, t, uls, ult, lrs, lrt)                \
    gDPLoadTileGeneric(pkt, G_SETTILESIZE, t, uls, ult, lrs, lrt)

#define gDPSetTile(pkt, fmt, siz, line, tmem, tile, palette, cmt,    \
        maskt, shiftt, cms, masks, shifts)                           \
{                                                                    \
    Gfx *_g = (Gfx *)(pkt);                                          \
                                                                     \
    _g->words.w0 = _SHIFTL(G_SETTILE, 24, 8) | _SHIFTL(fmt, 21, 3) | \
    _SHIFTL(siz, 19, 2) | _SHIFTL(line, 9, 9) |                      \
    _SHIFTL(tmem, 0, 9);                                             \
    _g->words.w1 = _SHIFTL(tile, 24, 3) | _SHIFTL(palette, 20, 4) |  \
    _SHIFTL(cmt, 18, 2) | _SHIFTL(maskt, 14, 4) |                    \
    _SHIFTL(shiftt, 10, 4) |_SHIFTL(cms, 8, 2) |                     \
    _SHIFTL(masks, 4, 4) | _SHIFTL(shifts, 0, 4);                    \
}

/*
 *  For RCP 2.0, the maximum number of texels that can be loaded
 *  using a load_block command is 2048.  In order to load the total
 *  4kB of Tmem, change the texel size when loading to be G_IM_SIZ_16b,
 *  then change the tile to the proper texel size after the load.
 *  The g*DPLoadTextureBlock macros already do this, so this change
 *  will be transparent if you use these macros.  If you use
 *  the g*DPLoadBlock macros directly, you will need to handle this
 *  tile manipulation yourself.  RJM.
 */
#define gDPLoadBlock(pkt, tile, uls, ult, lrs, dxt)          \
{                                                            \
    Gfx *_g = (Gfx *)(pkt);                                  \
                                                             \
    _g->words.w0 = (_SHIFTL(G_LOADBLOCK, 24, 8) |            \
            _SHIFTL(uls, 12, 12) | _SHIFTL(ult, 0, 12));     \
    _g->words.w1 = (_SHIFTL(tile, 24, 3) |                   \
            _SHIFTL((MIN(lrs,G_TX_LDBLK_MAX_TXL)), 12, 12) | \
            _SHIFTL(dxt, 0, 12));                            \
}

#define gsDPLoadBlock(tile, uls, ult, lrs, dxt)           \
{                                                         \
    (_SHIFTL(G_LOADBLOCK, 24, 8) | _SHIFTL(uls, 12, 12) | \
     _SHIFTL(ult, 0, 12)),                                \
    (_SHIFTL(tile, 24, 3) |                               \
     _SHIFTL((MIN(lrs,G_TX_LDBLK_MAX_TXL)), 12, 12) |     \
     _SHIFTL(dxt, 0, 12))                                 \
}

#define gDPLoadTextureBlock(pkt, timg, fmt, siz, width, height,   \
        pal, cms, cmt, masks, maskt, shifts, shiftt)              \
{                                                                 \
    gDPSetTextureImage(pkt, fmt, siz##_LOAD_BLOCK, 1, timg);      \
    gDPSetTile(pkt, fmt, siz##_LOAD_BLOCK, 0, 0, G_TX_LOADTILE,   \
            0 , cmt, maskt, shiftt, cms, masks, shifts);          \
    gDPLoadBlock(pkt, G_TX_LOADTILE, 0, 0,                        \
            (((width)*(height) + siz##_INCR) >> siz##_SHIFT) -1,  \
            CALC_DXT(width, siz##_BYTES));                        \
    gDPSetTile(pkt, fmt, siz,                                     \
            (((width) * siz##_LINE_BYTES)+7)>>3, 0,               \
            G_TX_RENDERTILE, pal, cmt, maskt, shiftt, cms, masks, \
            shifts);                                              \
    gDPSetTileSize(pkt, G_TX_RENDERTILE, 0, 0,                    \
            ((width)-1) << G_TEXTURE_IMAGE_FRAC,                  \
            ((height)-1) << G_TEXTURE_IMAGE_FRAC)                 \
}

#endif /* _GBI_H_ */
