#ifndef _IN_LIB_MODEL_H
#define _IN_LIB_MODEL_H
#include <ultra64.h>
#include "data.h"
#include "types.h"

extern bool (*var8005efc4)(struct model *model, struct modelnode *node);
extern Vtx *(*g_ModelVtxAllocatorFunc)(int numvertices);
extern void (*g_ModelJointPositionedFunc)(int mtxindex, Mtxf *mtx);

bool modelasm00018680(struct modelrenderdata *renderdata, struct model *model);
void modelSetDistanceChecksDisabled(bool disabled);
void modelSetDistanceScale(float value);
void modelSetVtxAllocatorFunc(Vtx *(*fn)(int numvertices));
int modelFindNodeMtxIndex(struct modelnode *node, int arg1);
Mtxf *modelFindNodeMtx(struct model *model, struct modelnode *node, int arg2);
Mtxf *modelGetRootMtx(struct model *model);
struct modelnode *modelFindNodeByMtxIndex(struct model *model, int mtxindex);
struct modelnode *modelNodeFindMtxNode(struct modelnode *node);
struct modelnode *modelNodeFindParentMtxNode(struct modelnode *node);
struct modelnode *modelNodeFindChildMtxNode(struct modelnode *node);
struct modelnode *modelNodeFindChildOrParentMtxNode(struct modelnode *node);
struct modelnode *modelGetPart(struct modeldef *arg0, int partnum);
void *modelGetPartRodata(struct modeldef *modeldef, int partnum);
float modelGetScreenDistance(struct model *model);
void *modelGetNodeRwData(struct model *model, struct modelnode *node);
void modelNodeGetPosition(struct model *model, struct modelnode *node, struct coord *pos);
void modelNodeSetPosition(struct model *model, struct modelnode *node, struct coord *pos);
void modelGetRootPosition(struct model *model, struct coord *pos);
void modelSetRootPosition(struct model *model, struct coord *pos);
void modelNodeGetModelRelativePosition(struct model *model, struct modelnode *node, struct coord *pos);
float modelGetChrRotY(struct model *model);
void modelSetChrRotY(struct model *model, float angle);
void modelSetScale(struct model *model, float scale);
void modelSetAnimScale(struct model *model, float scale);
float modelGetEffectiveScale(struct model *model);
void modelTweenPos(struct coord *pos, struct coord *to, float frac);
float modelTweenRotAxis(float arg0, float angle, float frac);
void modelTweenRot(struct coord *arg0, struct coord *arg1, float mult);
void modelUpdateChrInfo(struct model *model, struct modelnode *node);
void modelUpdateInfo(struct model *model);
void modelUpdateChrNodeMtx(struct modelrenderdata *arg0, struct model *model, struct modelnode *node);
void modelPositionJointUsingVecRot(struct modelrenderdata *renderdata, struct model *model, struct modelnode *node, struct coord *rot, struct coord *pos, bool allowscale, struct coord *arg6);
void modelPositionJointUsingQuatRot(struct modelrenderdata *renderdata, struct model *model, struct modelnode *node, float rot[4], struct coord *pos, struct coord *arg5);
void modelUpdatePositionNodeMtx(struct modelrenderdata *arg0, struct model *model, struct modelnode *node);
void modelUpdatePositionHeldNodeMtx(struct modelrenderdata *arg0, struct model *model, struct modelnode *node);
void modelUpdateDistanceRelations(struct model *model, struct modelnode *node);
void modelApplyDistanceRelations(struct model *model, struct modelnode *node);
void modelApplyToggleRelations(struct model *model, struct modelnode *node);
void modelApplyHeadRelations(struct model *model, struct modelnode *node);
void modelApplyReorderRelationsByArg(struct modelnode *basenode, bool reverse);
void modelApplyReorderRelations(struct model *model, struct modelnode *node);
void modelUpdateReorderRelations(struct model *model, struct modelnode *node);
void modelUpdateRelationsQuick(struct model *model, struct modelnode *node);
void modelUpdateRelations(struct model *model);
void modelUpdateMatrices(struct modelrenderdata *arg0, struct model *model);
void modelSetMatrices(struct modelrenderdata *arg0, struct model *model);
void modelSetMatricesWithAnim(struct modelrenderdata *renderdata, struct model *model);
int16_t modelGetAnimNum(struct model *model);
bool modelIsFlipped(struct model *model);
float modelGetCurAnimFrame(struct model *model);
float modelGetAnimEndFrame(struct model *model);
int modelGetNumAnimFrames(struct model *model);
float modelGetAnimSpeed(struct model *model);
float modelGetAbsAnimSpeed(struct model *model);
int modelConstrainOrWrapAnimFrame(int frame, int16_t animnum, float endframe);
void modelCopyAnimForMerge(struct model *model, float merge);
void modelSetAnimation2(struct model *model, int16_t animnum, int flip, float fstartframe, float speed, float merge);
bool modelIsAnimMerging(struct model *model);
void modelSetAnimationWithMerge(struct model *model, int16_t animnum, uint32_t flip, float startframe, float speed, float timemerge, bool domerge);
void modelSetAnimation(struct model *model, int16_t animnum, int flip, float fstartframe, float speed, float merge);
void modelCopyAnimData(struct model *src, struct model *dst);
void modelSetAnimLooping(struct model *model, float loopframe, float loopmerge);
void modelSetAnimEndFrame(struct model *model, float endframe);
void modelSetAnimFlipFunction(struct model *model, void *callback);
void modelSetAnimSpeed(struct model *model, float speed, float startframe);
void modelSetAnimSpeedAuto(struct model *model, float arg1, float startframe);
void modelSetAnimPlaySpeed(struct model *model, float speed, float frame);
void modelSetAnim70(struct model *model, void *callback);
void modelSetAnimFrame(struct model *model, float startframe);
void modelSetAnimFrame2(struct model *model, float arg1, float arg2);
void modelSetAnimMergingEnabled(bool value);
bool modelIsAnimMergingEnabled(void);
void modelSetAnimFrame2WithChrStuff(struct model *model, float frame, float arg2, float frame2, float arg4);
void modelTickAnimQuarterSpeed(struct model *model, int lvupdate240, bool arg2);
void modelTickAnim(struct model *model, int lvupdate240, bool arg2);
void modelApplyRenderModeType1(struct modelrenderdata *renderdata);
void modelApplyRenderModeType3(struct modelrenderdata *renderdata, bool arg1);
void modelApplyRenderModeType4(struct modelrenderdata *renderdata, bool arg1);
void modelApplyRenderModeType2(struct modelrenderdata *renderdata);
void modelApplyCullMode(struct modelrenderdata *renderdata);
void modelRenderNodeGundl(struct modelrenderdata *renderdata, struct model *model, struct modelnode *node);
void modelRenderNodeDl(struct modelrenderdata *renderdata, struct model *model, struct modelnode *node);
void modelRenderNodeStarGunfire(struct modelrenderdata *renderdata, struct modelnode *node);
void modelSelectTexture(struct modelrenderdata *renderdata, struct textureconfig *tconfig, int arg2);
void modelRenderNodeChrGunfire(struct modelrenderdata *renderdata, struct model *model, struct modelnode *node);
void modelRender(struct modelrenderdata *renderdata, struct model *model);
bool modelTestBboxNodeForHit(struct modelrodata_bbox *bbox, Mtxf *mtx, struct coord *arg2, struct coord *arg3);
int modelTestForHit(struct model *model, struct coord *arg1, struct coord *arg2, struct modelnode **startnode);
void modelPromoteNodeOffsetsToPointers(struct modelnode *node, uint32_t vma, uintptr_t fileramaddr);
void modelPromoteOffsetsToPointers(struct modeldef *modeldef, uint32_t arg1, uintptr_t arg2);
int modelCalculateRwDataIndexes(struct modelnode *node);
void modelAllocateRwData(struct modeldef *modeldef);
void modelInitRwData(struct model *model, struct modelnode *node);
void modelInit(struct model *model, struct modeldef *modeldef, uint32_t *rwdatas, bool resetanim);
void animInit(struct anim *anim);
void modelAttachHead(struct model *model, struct modeldef *arg1, struct modelnode *node, struct modeldef *arg3);
void modelIterateDisplayLists(struct modeldef *modeldef, struct modelnode **nodeptr, Gfx **gdlptr);
void modelNodeReplaceGdl(struct modeldef *modeldef, struct modelnode *node, Gfx *find, Gfx *replacement);

#endif
