#pragma once

#include <ultra64.h>
#include <stdint.h>
#include "data.h"
#include "types.h"

void bgunReset(void);

void bgunStop(void);

void bgunRumble(int handnum, int weaponnum);
int bgunGetUnequippedReloadIndex(int weaponnum);
void bgunTickUnequippedReload(void);
bool bgunTestGunVisCommand(struct gunviscmd *cmd, struct hand *hand);
void bgunSetPartVisible(int16_t partnum, bool visible, struct hand *hand, struct modeldef *modeldef);
void bgunExecuteGunVisCommands(struct hand *hand, struct modeldef *arg1, struct gunviscmd *command);
void bgun0f098030(struct hand *hand, struct modeldef *arg1);
float bgun0f09815c(struct hand *hand);
void bgun0f0981e8(struct hand *hand, struct modeldef *modeldef);
bool bgun0f098884(struct guncmd *cmd, struct gset *gset);
void bgunStartAnimation(struct guncmd *cmd, int handnum, struct hand *hand);
bool bgun0f098a44(struct hand *hand, int time);
bool bgunIsAnimBusy(struct hand *hand);
void bgunResetAnim(struct hand *hand);
void bgunGetWeaponInfo(struct handweaponinfo *info, int handnum);
int bgunDetermineReloadType(int arg0, struct handweaponinfo *info, struct hand *hand);
void bgunRefillMagazine(int weaponfunc, struct handweaponinfo *info, struct hand *hand, uint8_t onebullet, uint8_t checkunequipped);
void bgunFillMagazine(struct handweaponinfo *info, struct hand *hand);
bool bgunDetermineReloadTypeByHand(int handnum);
bool bgun0f0990b0(struct weaponfunc *basefunc, struct weapon *weapon);
bool bgun0f099188(struct hand *hand, int gunfunc);
int bgunTickIncIdle(struct handweaponinfo *info, int handnum, struct hand *hand, int lvupdate);
void bgunSetArmPitch(struct hand *hand, float angle);
int bgunTickIncAutoSwitch(struct handweaponinfo *info, int handnum, struct hand *hand, int lvupdate);
bool bgunIsReloading(struct hand *hand);
int bgunTickIncReload(struct handweaponinfo *info, int handnum, struct hand *hand, int lvupdate);
int bgunTickIncChangeFunc(struct handweaponinfo *info, int handnum, struct hand *hand, int lvupdate);
int bgunAttemptFire(struct hand *hand, struct weaponfunc *func);
void bgun0f09a6f8(struct handweaponinfo *info, int handnum, struct hand *hand, struct weaponfunc *func);
bool bgun0f09aba4(struct hand *hand, struct handweaponinfo *info, int handnum, struct weaponfunc_shoot *func);
bool bgunTickIncAttackingShoot(struct handweaponinfo *info, int handnum, struct hand *hand);
bool bgunTickIncAttackingThrow(int handnum, struct hand *hand);
int bgunGetMinClipQty(int weaponnum, int funcnum);
bool bgunTickIncAttackingMelee(int handnum, struct hand *hand);
bool bgunTickIncAttackingSpecial(struct hand *hand);
int bgunTickIncAttackEmpty(struct handweaponinfo *info, int handnum, struct hand *hand, int lvupdate);
int bgunTickIncAttack(struct handweaponinfo *info, int handnum, struct hand *hand, int lvupdate);
bool bgunIsReadyToSwitch(int handnum);
bool bgunCanFreeWeapon(int handnum);
bool bgun0f09bf44(int handnum);
int bgunTickIncChangeGun(struct handweaponinfo *info, int handnum, struct hand *hand, int lvupdate);
int bgunTickIncState2(struct handweaponinfo *info, int handnum, struct hand *hand, int lvupdate);
int bgunTickInc(struct handweaponinfo *info, int handnum, int lvupdate);
bool bgunSetState(int handnum, int state);
void bgunTickHand(int handnum);
void bgunTickSwitch(void);
void bgunInitHandAnims(void);
float bgunGetNoiseRadius(int handnum);
void bgunDecreaseNoiseRadius(void);
void bgunCalculateBlend(int hand);
void bgunUpdateBlend(struct hand *hand, int handnum);
void bgun0f09d8dc(float breathing, float arg1, float arg2, float arg3, float arg4);
bool bgunIsLoaded(void);
uint32_t bgunGetGunMemType(void);
uint8_t *bgunGetGunMem(void);
uint32_t bgunCalculateGunMemCapacity(void);
void bgunFreeGunMem(void);
void bgunSetGunMemWeapon(int weaponnum);
void bgunEnterFlux(void);
bool bgunChangeGunMem(int newowner);
void bgunTickGunLoad(void);
void bgunTickMasterLoad(void);
void bgunTickLoad(void);
bool bgunLoadAll(void);
struct modeldef *bgunGetCartModeldef(void);
void bgunCreateXBowBolt(struct defaultobj *obj, struct coord *coord, RoomNum *rooms, Mtxf *matrix1, struct coord *velocity, Mtxf *matrix2, struct prop *prop, struct coord *pos);
void bgun0f09ed2c(struct defaultobj *obj, struct coord *coord, Mtxf *arg2, struct coord *velocity, Mtxf *arg4);
struct defaultobj *bgunCreateThrownProjectile2(struct chrdata *chr, struct gset *gset, struct coord *pos, RoomNum *rooms, Mtxf *arg4, struct coord *velocity);
void bgunCreateThrownProjectile(int handnum, struct gset *gset);
void bgunUpdateHeldRocket(int handnum);
void bgunCreateHeldRocket(int handnum, struct weaponfunc_shootprojectile *func);
void bgunFreeHeldRocket(int handnum);
void bgunCreateFiredProjectile(int handnum);
void bgunSwivel(float autoaimx, float autoaimy, float crossdamp, float aimdamp);
void bgunSwivelWithDamp(float screenx, float screeny, float damp);
void bgunSwivelWithoutDamp(float arg0, float arg1);
void bgunGetCrossPos(float *x, float *y);
void bgun0f0a0c08(struct coord *arg0, struct coord *arg1);
void bgun0f0a0c44(int handnum, struct coord *arg1, struct coord *arg2);
void bgunCalculatePlayerShotSpread(struct coord *arg0, struct coord *arg1, int handnum, bool dorandom);
void bgunCalculateBotShotSpread(struct coord *arg0, int weaponnum, int funcnum, bool arg3, int crouchpos, bool dual);
void bgunSetLastShootInfo(struct coord *pos, struct coord *dir, int handnum);
int bgunGetShotsToTake(int handnum);
void bgunFreeWeapon(int handnum);
void bgunTickSwitch2(void);
void bgunEquipWeapon(int weaponnum);
int bgunGetWeaponNum(int handnum);
bool bgun0f0a1a10(int weaponnum);
int bgunGetSwitchToWeapon(int handnum);
void bgunSwitchToPrevious(void);
void bgunCycleForward(void);
void bgunCycleBack(void);
bool bgunHasAmmoForWeapon(int weaponnum);
void bgunAutoSwitchWeapon(void);
void bgunEquipWeapon2(int handnum, int weaponnum);
int bgunIsFiring(int handnum);
int bgunGetAttackType(int handnum);
char *bgunGetName(int weaponnum);
uint16_t bgunGetNameId(int weaponnum);
char *bgunGetShortName(int arg0);
void bgunReloadIfPossible(int handnum);
void bgunSetAdjustPos(float angle);
void bgunStartSlide(int handnum);
void bgunUpdateSlide(int handnum);
float bgun0f0a2498(float arg0, float arg1, float arg2, float arg3);
void bgun0f0a24f0(struct coord *arg0, int handnum);
bool bgun0f0a27c8(void);
void bgunHandlePlayerDead(void);
bool bgunIsMissionCritical(int weaponnum);
void bgunDisarm(struct prop *attacker);
void bgunExecuteModelCmdList(uintptr_t *arg0);
int bgunCreateModelCmdList(struct model *model, struct modelnode *node, uintptr_t *ptr);
void bgunStartDetonateAnimation(int playernum);
void bgunUpdateGangsta(struct hand *hand, int handnum, struct coord *arg2, struct weaponfunc *funcdef, Mtxf *arg4, Mtxf *arg5);
void bgunUpdateSmoke(struct hand *hand, int handnum, int weaponnum, struct weaponfunc *funcdef);
void bgunUpdateLasersight(struct hand *hand, struct modeldef *modeldef, int handnum, uint8_t *allocation);
void bgunUpdateReaper(struct hand *hand, struct modeldef *modeldef);
void bgunUpdateSniperRifle(struct modeldef *modeldef, uint8_t *allocation);
void bgunUpdateDevastator(struct hand *hand, uint8_t *allocation, struct modeldef *modeldef);
void bgunUpdateShotgun(struct hand *hand, uint8_t *allocation, bool *arg2, struct modeldef *modeldef);
void bgunUpdateLaser(struct hand *hand);
void bgunUpdateMagnum(struct hand *hand, int handnum, struct modeldef *modeldef, Mtxf *mtx);
void bgunUpdateRocketLauncher(struct hand *hand, int handnum, struct weaponfunc_shootprojectile *func);
void bgun0f0a45d0(struct hand *hand, struct modeldef *modeldef, bool isdetonator);
void bgunTickEject(struct hand *hand, struct modeldef *modeldef, bool isdetonator);
void bgun0f0a4e44(struct hand *hand, struct weapon *weapondef, struct modeldef *modeldef, struct weaponfunc *funcdef, int maxburst, uint8_t *allocation, int weaponnum, bool **arg7, int mtxindex, Mtxf *arg9, Mtxf *arg10);
void bgunCreateFx(struct hand *hand, int handnum, struct weaponfunc *funcdef, int weaponnum, struct modeldef *modeldef, uint8_t *allocation);
void bgun0f0a5550(int handnum);
void bgunTickMaulerCharge(void);
void bgunTickGameplay2(void);
int bgunAllocateFireslot(void);
void bgunRender(Gfx **gdl);
struct sndstate **bgunAllocateAudioHandle(void);
void bgunPlayPropHitSound(struct gset *gset, struct prop *prop, int texturenum);
void bgunPlayGlassHitSound(struct coord *pos, RoomNum *rooms, int texturenum);
void bgunPlayBgHitSound(struct gset *gset, struct coord *hitpos, int texturenum, RoomNum *rooms);
void bgunSetTriggerOn(int handnum, bool on);
int bgunConsiderToggleGunFunction(int usedowntime, bool trigpressed, bool fromactivemenu, bool fromdedicatedbutton);
void bgunDisallowInvertFunc(void);
bool bgunIsUsingSecondaryFunction(void);
void bgunTickGameplay(bool triggeron);
void bgunSetPassiveMode(bool enable);
void bgunSetAimType(uint32_t aimtype);
void bgunSetAimPos(struct coord *coord);
void bgunSetHitPos(struct coord *coord);
void bgun0f0a9494(uint32_t operation);
void bgun0f0a94d0(uint32_t operation, struct coord *pos, struct coord *rot);
void bgunSetGunAmmoVisible(uint32_t reason, bool enable);
void bgunSetAmmoQuantity(int ammotype, int quantity);
int bgunGetReservedAmmoCount(int type);
int bgunGetAmmoCount(int ammotype);
int bgunGetCapacityByAmmotype(int ammotype);
bool bgunAmmotypeAllowsUnlimitedAmmo(uint32_t ammotype);
void bgunGiveMaxAmmo(bool force);
uint32_t bgunGetAmmoTypeForWeapon(uint32_t weaponnum, uint32_t func);
int bgunGetAmmoQtyForWeapon(uint32_t weaponnum, uint32_t func);
void bgunSetAmmoQtyForWeapon(uint32_t weaponnum, uint32_t func, uint32_t quantity);
int bgunGetAmmoCapacityForWeapon(int weaponnum, int func);
Gfx *bgunDrawHudString(Gfx *gdl, char *text, int x, bool halign, int y, int valign, uint32_t colour);
Gfx *bgunDrawHudInteger(Gfx *gdl, int value, int x, bool halign, int y, int valign, uint32_t colour);
void bgunResetAbmag(struct abmag *abmag);
void bgun0f0a9da8(struct abmag *abmag, int remaining, int capacity, int height);
Gfx *bgunDrawHudGauge(Gfx *gdl, int x1, int y1, int x2, int y2, struct abmag *abmag, int remaining, int capacity, uint32_t vacantcolour, uint32_t occupiedcolour, bool flip);
Gfx *bgunDrawHud(Gfx *gdl);
void bgunAddBoost(int arg0);
void bgunSubtractBoost(int arg0);
void bgunApplyBoost(void);
void bgunRevertBoost(void);
void bgunTickBoost(void);
void bgunSetSightVisible(uint32_t bits, bool visible);
Gfx *bgunDrawSight(Gfx *gdl);
void bgun0f0abd30(int handnum);
int bgunGetWeaponNum2(int handnum);
int8_t bgunFreeFireslotWrapper(int fireslot);
int8_t bgunFreeFireslot(int fireslot);
