#ifndef _IN_GAME_CHR_CHRACTION_H
#define _IN_GAME_CHR_CHRACTION_H
#include <ultra64.h>
#include <stdint.h>
#include "data.h"
#include "types.h"

float func0f02dff0(int16_t animnum);
bool chrGoPosIsWaiting(struct chrdata *chr);
bool weaponIsOneHanded(struct prop *prop);
float chrGetRangedSpeed(struct chrdata *chr, float min, float max);
int chrGetPercentageOfSlowness(struct chrdata *chr, int percentage);
float chrGetRangedArghSpeed(struct chrdata *chr, float min, float max);
float chrGetAttackEntityRelativeAngle(struct chrdata *chr, int attackflags, int entityid);
float chrGetAttackEntityDistance(struct chrdata *chr, uint32_t attackflags, int entityid);
void func0f02e3dc(struct coord *a, struct coord *b, struct coord *c, struct coord *d, struct coord *dst);
void func0f02e4f8(struct coord *arg0, struct coord *arg1, struct coord *dst);
float func0f02e550(struct prop *prop, float arg1, float arg2, uint32_t cdtypes, float ymax, float ymin);
float func0f02e684(struct prop *prop, float arg1, float arg2);
void chrChooseStandAnimation(struct chrdata *chr, float mergetime);
void chrStand(struct chrdata *chr);
bool chrFaceCover(struct chrdata *chr);
void chrKneelChooseAnimation(struct chrdata *chr);
void chrStartAlarmChooseAnimation(struct chrdata *chr);
void chrThrowGrenadeChooseAnimation(struct chrdata *chr);
void chrSurprisedChooseAnimation(struct chrdata *chr);
void chrDoSurprisedOneHand(struct chrdata *chr);
void chrSurrenderChooseAnimation(struct chrdata *chr);
void chrSidestepChooseAnimation(struct chrdata *chr);
void chrJumpOutChooseAnimation(struct chrdata *chr);
void chrRunPosChooseAnimation(struct chrdata *chr);
void chrAttackStand(struct chrdata *chr, uint32_t attackflags, int entityid);
void chrAttackLie(struct chrdata *chr, uint32_t attackflags, int entityid);
void chrAttackKneel(struct chrdata *chr, uint32_t attackflags, int entityid);
void chrAttackWalkChooseAnimation(struct chrdata *chr);
void chrAttackWalk(struct chrdata *chr, bool run);
void chrAttackRollChooseAnimation(struct chrdata *chr);
void chrAttackRoll(struct chrdata *chr, bool toleft);
void chrStartAnim(struct chrdata *chr, int animnum, float startframe, float endframe, uint8_t chranimflags, int merge, float speed);
void func0f031254(struct chrdata *chr);
void chrAttack(struct chrdata *chr, struct attackanimgroup **animgroups, bool flip, bool *firing, uint32_t attackflags, int entityid, bool standing);
void chrAttackAmount(struct chrdata *chr, uint32_t attackflags, uint32_t entityid, uint32_t maxshots);
void chrBeginDeath(struct chrdata *chr, struct coord *dir, float relangle, int hitpart, struct gset *gset, bool knockout, int aplayernum);
void chrBeginArgh(struct chrdata *chr, float angle, int hitpart);
void chrReactToDamage(struct chrdata *chr, struct coord *dir, float angle, int hitpart, struct gset *gset, int playernum);
void chrYeetFromPos(struct chrdata *chr, struct coord *pos, float arg2);
int gsetGetBlurAmount(struct gset *gset);
void chrKnockOut(struct chrdata *chr, float angle, int hitpart, struct gset *gset);
bool chrIsAnimPreventingArgh(struct chrdata *chr, float *arg1);
void chrChoke(struct chrdata *chr, int choketype);
void chrSetShield(struct chrdata *chr, float shield);
bool func0f034080(struct chrdata *chr, struct modelnode *node, struct prop *prop, struct model *model, int side, int16_t *arg5);
void chrDamageByMisc(struct chrdata *chr, float damage, struct coord *vector, struct gset *gset, struct prop *prop);
void chrDamageByLaser(struct chrdata *chr, float damage, struct coord *vector, struct gset *gset, struct prop *prop);
void func0f0341dc(struct chrdata *chr, float damage, struct coord *vector, struct gset *gset, struct prop *prop, int hitpart, struct prop *prop2, struct modelnode *node, struct model *model, int side, int16_t *arg10);
void chrDamageByImpact(struct chrdata *chr, float damage, struct coord *vector, struct gset *gset, struct prop *prop, int arg5);
void chrDamageByExplosion(struct chrdata *chr, float damage, struct coord *vector, struct prop *prop, struct coord *explosionpos);
void playerUpdateDamageStats(struct prop *attacker, struct prop *victim, float damage);
void chrDamage(struct chrdata *chr, float damage, struct coord *vector, struct gset *gset, struct prop *aprop, int hitpart, bool damageshield, struct prop *prop2, struct modelnode *node, struct model *model, int side, int16_t *arg11, bool explosion, struct coord *explosionpos);
bool func0f03645c(struct chrdata *chr, struct coord *arg1, RoomNum *arg2, struct coord *arg3, struct coord *arg4, int cdtypes);
bool func0f03654c(struct chrdata *chr, struct coord *pos, RoomNum *rooms, struct coord *pos2, RoomNum *rooms2, struct coord *vector, float arg6, uint32_t types);
bool propchrHasClearLineToPos(struct prop *prop, struct coord *dstpos, struct coord *vector);
bool propchrHasClearLineInVector(struct prop *prop, struct coord *coord, float arg2);
bool func0f036974(struct prop *prop, struct coord *coord);
void chrGetSideVectorToTarget(struct chrdata *chr, bool side, struct coord *vector);
bool chrCanRollInDirection(struct chrdata *chr, bool toleft, float distance);
void chrGetSideVector(struct chrdata *chr, bool side, struct coord *vector);
bool chrCanJumpInDirection(struct chrdata *chr, bool side, float distance);
bool chrIsRoomOffScreen(struct chrdata *chr, struct coord *waypos, RoomNum *wayrooms);
void chrGoPosInitMagic(struct chrdata *chr, struct waydata *waydata, struct coord *arg2, struct coord *prevpos);
void chrGoPosGetCurWaypointInfoWithFlags(struct chrdata *chr, struct coord *pos, RoomNum *rooms, uint32_t *flags);
float func0f0370a8(struct chrdata *chr);
int chrGoPosCalculateBaseTtl(struct chrdata *chr);
void chrGoPosConsiderRestart(struct chrdata *chr);
void chrGoPosInitExpensive(struct chrdata *chr);
void chrGoPosAdvanceWaypoint(struct chrdata *chr);
int chrPatrolCalculateStep(struct chrdata *chr, bool *forward, int numsteps);
int16_t chrPatrolCalculatePadNum(struct chrdata *chr, int numsteps);
void chrPatrolGetCurWaypointInfoWithFlags(struct chrdata *chr, struct coord *pos, RoomNum *rooms, uint32_t *flags);
void func0f037580(struct chrdata *chr);
void func0f0375b0(struct chrdata *chr);
void chrNavTickMagic(struct chrdata *chr, struct waydata *waydata, float speed, struct coord *arg3, RoomNum *rooms);
void chrCalculatePosition(struct chrdata *chr, struct coord *pos);
void chrGoPosChooseAnimation(struct chrdata *chr);
bool chrGoToRoomPos(struct chrdata *chr, struct coord *pos, RoomNum *rooms, uint32_t goposflags);
void chrPatrolChooseAnimation(struct chrdata *chr);
void chrStartPatrol(struct chrdata *chr, struct path *path);
bool chrHasLosToEntity(struct chrdata *chr, struct coord *chrpos, RoomNum *chrrooms, bool allowextraheight, uint32_t attackflags, uint32_t entityid);
bool chrHasLosToAttackTarget(struct chrdata *chr, struct coord *pos, RoomNum *rooms, bool allowextraheight);
bool chrHasLosToChr(struct chrdata *chr, struct chrdata *target, RoomNum *room);
bool chrHasLosToPos(struct chrdata *viewerchr, struct coord *pos, RoomNum *rooms);
bool chrHasLosToPosWasteful(struct chrdata *chr, struct coord *pos, RoomNum *room);
bool chrHasLosToProp(struct chrdata *chr, struct prop *prop);
bool chrIsStopped(struct chrdata *chr);
bool chrCheckCanSeeTarget(struct chrdata *chr);
bool chrIsReadyForOrders(struct chrdata *chr);
bool chrTrySidestep(struct chrdata *chr);
bool chrTryJumpOut(struct chrdata *chr);
bool chrTryRunSideways(struct chrdata *chr);
bool chrTryAttackWalk(struct chrdata *chr);
bool chrTryAttackRun(struct chrdata *chr);
bool chrTryAttackRoll(struct chrdata *chr);
bool chrTryAttackAmount(struct chrdata *chr, uint32_t arg1, uint32_t arg2, uint8_t arg3, uint8_t arg4);
bool chrGoToPad(struct chrdata *chr, int padnum, uint32_t goposflags);
bool chrGoToPos(struct chrdata *chr, struct coord *pos, uint32_t goposflags);
int func0f03aca0(struct chrdata *chr, float arg1, uint8_t arg2);
bool chrTryRunFromTarget(struct chrdata *chr);
bool chrGoToCoverProp(struct chrdata *chr);
bool chrDropItem(struct chrdata *chr, uint32_t modelnum, uint32_t weaponnum);
void chrPunchInflictDamage(struct chrdata *chr, int damage, int range, uint8_t reverse);
bool chrTryPunch(struct chrdata *chr, uint8_t reverse);
struct eyespy *chrToEyespy(struct chrdata *chr);
void chrTickStand(struct chrdata *chr);
void chrTickAnim(struct chrdata *chr);
void chrTickSurrender(struct chrdata *chr);
void chrTickDead(struct chrdata *chr);
void chrAlertOthersOfInjury(struct chrdata *chr, bool dying);
void chrTickDie(struct chrdata *chr);
void chrTickDruggedComingUp(struct chrdata *chr);
void chrTickDruggedDrop(struct chrdata *chr);
void chrTickDruggedKo(struct chrdata *chr);
void chrTickArgh(struct chrdata *chr);
void chrTickPreArgh(struct chrdata *chr);
void chrTickSidestep(struct chrdata *chr);
void chrTickJumpOut(struct chrdata *chr);
void chrTickStartAlarm(struct chrdata *chr);
void chrTickSurprised(struct chrdata *chr);
void chrUpdateFireslot(struct chrdata *chr, int handnum, bool withsound, bool withbeam, struct coord *from, struct coord *to);
float chrGetInverseTheta(struct chrdata *chr);
float chrGetAimAngle(struct chrdata *chr);
float chrGetPitchAngle(struct chrdata *chr);
int chrTurn(struct chrdata *chr, int turning, float endanimframe, float speed, float toleranceangle);
bool func0f03e9f4(struct chrdata *chr, struct attackanimconfig *animcfg, int arg2, int arg3, float arg4);
void chrCalculateAimEndProperties(struct chrdata *chr, struct attackanimconfig *animcfg, bool firingleft, bool firingright, float shootrotx);
float chrGetAimLimitAngle(float sqdist);
void chrCalculateHit(struct chrdata *chr, bool *angleokptr, bool *hit, struct gset *gset);
bool chrGetGunPos(struct chrdata *chr, int handnum, struct coord *gunpos);
void chrCalculateShieldHit(struct chrdata *chr, struct coord *pos, struct coord *vector, struct modelnode **node, int *hitpart, struct model **model, int *side);
void chrCalculateTrajectory(struct coord *frompos, float arg1, struct coord *aimpos, struct coord *arg3);
void chrTickShoot(struct chrdata *chr, int handnum);
void func0f041a74(struct chrdata *chr);
bool func0f041c44(struct chrdata *chr);
void chrAttackAmountUpdateAnimation(struct chrdata *chr);
void chrTickFire(struct chrdata *chr);
void chrTickAttackAmount(struct chrdata *chr);
void robotSetMuzzleFlash(struct chrdata *chr, bool right, bool enabled);
void robotAttack(struct chrdata *chr);
void chrTickRobotAttack(struct chrdata *chr);
void chrTickAttack(struct chrdata *chr);
void chrTickAttackRoll(struct chrdata *chr);
void chrTickThrowGrenade(struct chrdata *chr);
bool func0f043f2c(struct chrdata *chr, struct coord *runpos, uint32_t arg2, float *turnspeed);
void chrTickAttackWalk(struct chrdata *chr);
bool posIsMovingTowardsPosOrStoppedInRange(struct coord *prevpos, struct coord *moveddelta, struct coord *targetpos, float range);
bool posIsArrivingLaterallyAtPos(struct coord *prevpos, struct coord *curpos, struct coord *targetpos, float range);
bool posIsArrivingAtPos(struct coord *prevpos, struct coord *curpos, struct coord *targetpos, float range);
void chrTickRunPos(struct chrdata *chr);
void func0f044b68(struct coord *arg0, struct coord *arg1, struct coord *arg2);
bool chrNavCanSeeNextPos(struct chrdata *chr, struct coord *pos, RoomNum *rooms, struct coord *aimpos, struct coord *arg4, struct coord *arg5, float negchrradius, float chrradius, int cdtypes, int arg9);
bool chrNavCheckForObstacle(struct chrdata *chr, struct coord *chrpos, RoomNum *chrrooms, struct coord *aimpos, struct coord *leftpos, struct coord *rightpos, float negchrradius, float chrradius, int cdtypes, bool hasobstacle);
bool chrNavTryObstacle(struct chrdata *chr, struct coord *arg1, bool arg2, struct coord *arg3, float radius, bool arg5, struct coord *nextpos, struct waydata *waydata, float arg8, int cdtypes, int arg10);
struct prop *chrOpenDoor(struct chrdata *chr, struct coord *rangepos);
void chrNavTickMain(struct chrdata *chr, struct coord *pos, struct waydata *waydata, bool arg3);
bool chrGoPosUpdateLiftAction(struct chrdata *chr, uint32_t curpadflags, bool arg2, bool arrivingatlift, int16_t curpadnum, int nextpadnum);
int16_t chrGoPosGetNextPadNum(struct chrdata *chr);
void chrTickGoPos(struct chrdata *chr);
void chrTickPatrol(struct chrdata *chr);
bool chrStartSkJump(struct chrdata *chr, uint8_t arg1, uint8_t arg2, int arg3, uint8_t arg4);
void chrTickSkJump(struct chrdata *chr);
void chraTick(struct chrdata *chr);
void cutsceneStart(uint32_t ailistid);
void chraTickBg(void);
float chrGetAngleToPos(struct chrdata *chr, struct coord *pos);
void chrGetAttackEntityPos(struct chrdata *chr, uint32_t attackflags, int entityid, struct coord *pos, RoomNum *rooms);
float chrGetAngleFromTargetsFov(struct chrdata *chr);
float chrGetVerticalAngleToTarget(struct chrdata *chr);
bool chrIsInTargetsFovX(struct chrdata *chr, uint8_t fov360);
bool chrIsVerticalAngleToTargetWithin(struct chrdata *chr, uint8_t arg1);
float chrGetAngleToTarget2(struct chrdata *chr, uint8_t reverse);
bool chrIsTargetInFov(struct chrdata *chr, uint8_t arg1, uint8_t reverse);
bool chrIsLookingAtPos(struct chrdata *chr, struct coord *pos, uint8_t arg2);
float chrGetSameFloorDistanceToPad(struct chrdata *chr, int pad_id);
void chrsClearRefsToPlayer(int playernum);
int chrResolveId(struct chrdata *ref, int id);
float chrGetTimer(struct chrdata *chr);
bool chrIsTargetAimingAtMe(struct chrdata *chr);
bool chrSawInjury(struct chrdata *chr, uint8_t arg1);
bool chrSawDeath(struct chrdata *chr, uint8_t arg1);
bool waypointIsWithin90DegreesOfPosAngle(struct waypoint *waypoint, struct coord *pos, float angle);
int chrFindWaypointWithinPosQuadrant(struct coord *pos, RoomNum *rooms, float angle, uint8_t quadrant);
bool func0f04a4ec(struct chrdata *chr, uint8_t quadrant);
bool chrSetPadPresetToWaypointWithinTargetQuadrant(struct chrdata *chr, uint8_t arg1);
bool chrSetChrPresetToChrNearPad(uint32_t checktype, struct chrdata *chr, float distance, int padnum);
bool chrSetChrPresetToChrNearPos(uint8_t checktype, struct chrdata *chr, float distance, struct coord *pos, RoomNum *room);
bool chrSetPadPresetToPadOnRouteToTarget(struct chrdata *chr);
bool chrIsPosOffScreen(struct coord *pos, RoomNum *rooms);
bool chrAdjustPosForSpawn(float chrradius, struct coord *pos, RoomNum *rooms, float angle, bool allowonscreen, bool force, bool onlysurrounding);
struct prop *chrSpawnAtCoord(int body, int head, struct coord *pos, RoomNum *room, float angle, uint8_t *ailist, uint32_t spawnflags);
bool chrIsPropPresetBlockingSightToTarget(struct chrdata *chr);
bool chrMoveToPos(struct chrdata *chr, struct coord *pos, RoomNum *room, float angle, bool ignorebg);
bool chrCheckCoverOutOfSight(struct chrdata *chr, int covernum, bool soft);
int chrAssignCoverByCriteria(struct chrdata *chr, uint16_t arg1, int arg2);
int chrAssignCoverAwayFromDanger(struct chrdata *chr, int mindist, int maxdist);
bool chrRunFromPos(struct chrdata *chr, uint32_t goposflags, float distance, struct coord *frompos);
float func0f04c784(struct chrdata *chr);
bool chr0f04c874(struct chrdata *chr, uint32_t angle360, struct coord *pos, uint8_t arg3, uint8_t arg4);
void rebuildTeams(void);
void rebuildSquadrons(void);
void chrAvoid(struct chrdata *chr);
void func0f02e9a0(struct chrdata *chr, float mergetime);
void func0f02ed28(struct chrdata *chr, float mergetime);
void chrStop(struct chrdata *chr);
void chrKneel(struct chrdata *chr);
void chrStartAlarm(struct chrdata *chr);
void chrThrowGrenade(struct chrdata *chr, int arg1, int arg2);
void chrSneeze(struct chrdata *chr);
void chrDoSurprisedSurrender(struct chrdata *chr);
void chrDoSurprisedLookAround(struct chrdata *chr);
void chrSurrender(struct chrdata *chr);
void chrSidestep(struct chrdata *chr, bool side);
void chrJumpOut(struct chrdata *chr, bool side);
void chrRunToPos(struct chrdata *chr, struct coord *pos);
void chrBeginDead(struct chrdata *chr);
float chrGetShield(struct chrdata *chr);
void chrDie(struct chrdata *chr, int aplayernum);
void chrGoPosGetCurWaypointInfo(struct chrdata *chr, struct coord *pos, RoomNum *rooms);
void chrGoPosClearRestartTtl(struct chrdata *chr);
void chrPatrolGetCurWaypointInfo(struct chrdata *chr, struct coord *pos, RoomNum *rooms);
struct path *pathFindById(uint32_t path_id);
void chrRecordLastVisibleTargetTime(struct chrdata *chr);
bool chrHasLosToTarget(struct chrdata *chr);
void chrRecordLastSeeTargetTime(struct chrdata *chr);
void chrRecordLastHearTargetTime(struct chrdata *chr);
bool chrIsDead(struct chrdata *chr);
bool chrTryAttackStand(struct chrdata *chr, uint32_t attackflags, int entityid);
bool chrTryAttackKneel(struct chrdata *chr, uint32_t attackflags, int entityid);
bool chrTryAttackLie(struct chrdata *chr, uint32_t attackflags, int entityid);
bool chrTryModifyAttack(struct chrdata *chr, uint32_t attackflags, int entityid);
bool chrFaceEntity(struct chrdata *chr, uint32_t attackflags, int entityid);
bool chrSetPath(struct chrdata *chr, uint32_t path_id);
bool chrTryStartPatrol(struct chrdata *chr);
bool chrTrySurrender(struct chrdata *chr);
bool chrFadeOut(struct chrdata *chr);
bool chrGoToTarget(struct chrdata *chr, uint32_t goposflags);
bool chrGoToChr(struct chrdata *chr, uint32_t dst_chrnum, uint32_t goposflags);
bool chrGoToProp(struct chrdata *chr, struct prop *prop, uint32_t goposflags);
bool chrTryStop(struct chrdata *chr);
bool chrTrySurprisedOneHand(struct chrdata *chr);
bool chrTrySurprisedSurrender(struct chrdata *chr);
bool chrTrySurprisedLookAround(struct chrdata *chr);
bool chrTryKneel(struct chrdata *chr);
bool chrTryStartAnim(struct chrdata *chr, int animnum, float startframe, float endframe, uint8_t chranimflags, int merge, float speed);
bool chrTryStartAlarm(struct chrdata *chr, int pad_id);
bool chrConsiderGrenadeThrow(struct chrdata *chr, uint32_t attackflags, uint32_t entityid);
void chrTickKneel(struct chrdata *chr);
void chrFadeCorpse(struct chrdata *chr);
void chrFadeCorpseWhenOffScreen(struct chrdata *chr);
void chrTickTest(struct chrdata *chr);
void chrSetLookAngle(struct chrdata *chr, float angle);
float chrGetRotY(struct chrdata *chr);
void chrSetRotY(struct chrdata *chr, float arg1);
void chrResetAimEndProperties(struct chrdata *chr);
void chrSetFiring(struct chrdata *chr, int hand, bool firing);
void chrStopFiring(struct chrdata *chr);
void chrSetHandFiring(struct chrdata *chr, int hand, bool arg2);
void func0f0429d8(struct chrdata *chr, float arg1, float arg2);
void propUnsetDangerous(struct prop *prop);
void propSetDangerous(struct prop *prop);
bool chrDetectDangerousObject(struct chrdata *chr, uint8_t flags);
void chrTickBondDie(struct chrdata *chr);
int chrIsUsingLift(struct chrdata *chr);
bool chrTrySkJump(struct chrdata *chr, uint8_t arg1, uint8_t arg2, int arg3, uint8_t arg4);
bool chrSawTargetRecently(struct chrdata *chr);
bool chrHeardTargetRecently(struct chrdata *chr);
float chrGetAngleToTarget(struct chrdata *chr);
float chrGetDistanceToTarget(struct chrdata *chr);
float chrGetDistanceToCurrentPlayer(struct chrdata *chr);
float propGetDistanceToProp(struct prop *a, struct prop *b);
float propGetLateralDistanceToProp(struct prop *a, struct prop *b);
float chrGetDistanceToPad(struct chrdata *chr, int pad_id);
float chrGetDistanceToCoord(struct chrdata *chr, struct coord *pos);
float chrGetLateralDistanceToCoord(struct chrdata *chr, struct coord *pos);
float chrGetLateralDistanceToPad(struct chrdata *chr, int pad_id);
float chrGetSquaredDistanceToCoord(struct chrdata *chr, struct coord *pos);
float coordGetSquaredDistanceToCoord(struct coord *a, struct coord *b);
int chrGetPadRoom(struct chrdata *chr, int pad_id);
int chrResolvePadId(struct chrdata *chr, int pad_id);
struct chrdata *chrFindById(struct chrdata *data, int chrnum);
int propGetIndexByChrId(struct chrdata *chr, int chrnum);
float chrGetDistanceToChr(struct chrdata *chr1, int chr2num);
float chrGetDistanceFromTargetToPad(struct chrdata *chr, int pad_id);
void chrSetFlags(struct chrdata *chr, uint32_t flags, uint8_t bank);
void chrUnsetFlags(struct chrdata *chr, uint32_t flags, uint8_t bank);
bool chrHasFlag(struct chrdata *chr, uint32_t flag, uint8_t bank);
void chrSetFlagsById(struct chrdata *ref, uint32_t chrnum, uint32_t flags, uint32_t bank);
void chrUnsetFlagsById(struct chrdata *ref, uint32_t chrnum, uint32_t flags, uint32_t bank);
bool chrHasFlagById(struct chrdata *ref, uint32_t chrnum, uint32_t flag, uint32_t bank);
void chrSetStageFlag(struct chrdata *chr, uint32_t flag);
void chrUnsetStageFlag(struct chrdata *chr, uint32_t flag);
bool chrHasStageFlag(struct chrdata *chr, uint32_t flag);
bool chrIsHearingTarget(struct chrdata *chr);
void chrRestartTimer(struct chrdata *chr);
bool chrResetNearMiss(struct chrdata *chr);
int chrGetNumArghs(struct chrdata *chr);
int chrGetNumCloseArghs(struct chrdata *chr);
void decrementByte(uint8_t *dst, uint8_t amount);
void incrementByte(uint8_t *dst, uint8_t amount);
bool chrCanHearAlarm(struct chrdata *chr);
bool chrSetChrPresetToAnyChrNearSelf(struct chrdata *chr, float distance);
bool chrSetChrPresetToChrNearSelf(uint8_t checktype, struct chrdata *chr, float distance);
bool chrCompareTeams(struct chrdata *chr1, struct chrdata *chr2, uint8_t checktype);
void chrSetChrPreset(struct chrdata *chr, int chrpreset);
void chrSetChrPresetByChrnum(struct chrdata *chr, int chrnum, int chrpreset);
void chrSetPadPreset(struct chrdata *chr, int pad_id);
void chrSetPadPresetByChrnum(struct chrdata *chr, int chrnum, int pad_id);
struct prop *chrSpawnAtPad(struct chrdata *chr, int body, int head, int pad, uint8_t *ailist, uint32_t spawnflags);
struct prop *chrSpawnAtChr(struct chrdata *basechr, int body, int head, uint32_t chrnum, uint8_t *ailist, uint32_t spawnflags);
int16_t chrGoToCover(struct chrdata *chr, uint8_t speed);
void chrAddTargetToBdlist(struct chrdata *chr);
int chrGetDistanceLostToTargetInLastSecond(struct chrdata *chr);
bool chrIsTargetNearlyInSight(struct chrdata *chr, uint32_t distance);
bool chrIsNearlyInTargetsSight(struct chrdata *chr, uint32_t distance);
int16_t *teamGetChrIds(int team_id);
int16_t *squadronGetChrIds(int squadron_id);
void audioMarkAsRecentlyPlayed(int16_t audioid);
bool audioWasNotPlayedRecently(int16_t audioid);
void chrToggleModelPart(struct chrdata *chr, int partnum);
bool chrIsAvoiding(struct chrdata *chr);
void chrDrCarollEmitSparks(struct chrdata *chr);

#endif
