#pragma once

#include "data.h"
#include "types.h"

extern uint16_t g_ControlStyleOptions[];

extern struct menudialogdef g_AcceptMissionMenuDialog;
extern struct menudialogdef g_PreAndPostMissionBriefingMenuDialog;
extern struct menudialogdef g_RetryMissionMenuDialog;
extern struct menudialogdef g_NextMissionMenuDialog;
extern struct menudialogdef g_ExitGameMenuDialog;

char *menuTextCurrentStageName(struct menuitem *item);
char *soloMenuTextDifficulty(struct menuitem *item);
MenuItemHandlerResult menuhandlerControlStyleImpl(int operation, struct menuitem *item, union handlerdata *data, int mpindex);
char *soloMenuTitleStageOverview(struct menudialogdef *dialogdef);
float func0f1036ac(uint8_t value, int prop);
bool isStageDifficultyUnlocked(int stageindex, int difficulty);
char *soloMenuTextBestTime(struct menuitem *item);
int getMaxAiBuddies(void);
int getNumUnlockedSpecialStages(void);
int func0f104720(int value);
char *func0f105664(struct menuitem *item);
char *func0f1056a0(struct menuitem *item);
char *invMenuTextPrimaryFunction(struct menuitem *item);
char *invMenuTextSecondaryFunction(struct menuitem *item);
void invMenuGetGunConfigs(int weaponnum);
char *invMenuTextWeaponName(struct menuitem *item);
char *invMenuTextWeaponManufacturer(struct menuitem *item);
char *invMenuTextWeaponDescription(struct menuitem *item);
bool soloChoosePauseDialog(void);
MenuDialogHandlerResult menudialogBriefing(int operation, struct menudialogdef *dialogdef, union handlerdata *data);
MenuDialogHandlerResult menudialog00103608(int operation, struct menudialogdef *dialogdef, union handlerdata *data);
MenuDialogHandlerResult menudialogCoopAntiOptions(int operation, struct menudialogdef *dialogdef, union handlerdata *data);
MenuDialogHandlerResult menudialog0010559c(int operation, struct menudialogdef *dialogdef, union handlerdata *data);
MenuDialogHandlerResult inventoryMenuDialog(int operation, struct menudialogdef *dialogdef, union handlerdata *data);
MenuDialogHandlerResult menudialogAbortMission(int operation, struct menudialogdef *dialogdef, union handlerdata *data);
MenuDialogHandlerResult soloMenuDialogPauseStatus(int operation, struct menudialogdef *dialogdef, union handlerdata *data);
MenuItemHandlerResult menuhandler001024dc(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandler001024fc(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerAcceptMission(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerAcceptPdModeSettings(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerBuddyOptionsContinue(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerCoopDifficulty(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerAntiDifficulty(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMissionList(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerControlStyle(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerFrInventoryList(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerInventoryList(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerAbortMission(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerCinema(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerAimControl(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerAlternativeTitle(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerAlwaysShowTarget(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerAmmoOnScreen(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerAntiPlayer(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerAntiRadar(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerAutoAim(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerChangeAgent(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerCoopBuddy(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerCoopFriendlyFire(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerCoopRadar(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerCutsceneSubtitles(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerHeadRoll(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerInGameSubtitles(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerLangFilter(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerLookAhead(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerMusicVolume(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerPaintball(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerPdMode(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerPdModeSetting(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerReversePitch(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerScreenRatio(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerScreenSize(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerScreenSplit(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerSfxVolume(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerShowGunFunction(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerShowMissionTime(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerShowZoomRange(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerSightOnScreen(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerSoloDifficulty(int operation, struct menuitem *item, union handlerdata *data);
MenuItemHandlerResult menuhandlerSoundMode(int operation, struct menuitem *item, union handlerdata *data);