#pragma once

#include "data.h"
#include "types.h"

void mtxLoadRandomRotation(Mtx *mtx);
void mtxRandomToss(struct coord *arg0, Mtx *mtx);
void integrateDampedMotion(float *arg0, float *arg1, float arg2);
void mtxApplyRotation(Mtx *arg0, Mtx *arg1, int count);
void mtxAlign(Mtx *m, float a, float x, float y, float z);
void mtx4MultMtx4InPlace(Mtx *multmtx, Mtx *subject);
void mtx4MultMtx4(Mtx *mtx1, Mtx *mtx2, Mtx *dst);
void mtxIdent(Mtx *m);
void mtxScale(Mtx *m, float x, float y, float z);
void mtxScaleRow0Full(float arg0, Mtx *mtx);
void mtxScaleRow0Vec(float mult, Mtx *mtx);
void mtxScaleRow1Full(float arg0, Mtx *mtx);
void mtxScaleRow1Vec(float mult, Mtx *mtx);
void mtxScaleRow2Full(float arg0, Mtx *mtx);
void mtxScaleRow2Vec(float mult, Mtx *mtx);
void mtxScaleRotationPart(float mult, Mtx *mtx);
void mtxRotate(Mtx *m, float a, float x, float y, float z);
void mtx4RotateVecInPlace(Mtx *mtx, struct coord *vec);
void mtx4RotateVec(Mtx *mtx, struct coord *vec, struct coord *dst);
void mtx4TransformVecInPlace(Mtx *mtx, struct coord *vec);
void mtx4TransformVec(Mtx *mtx, struct coord *vec, struct coord *dst);
void mtx4SetTranslation(struct coord *pos, Mtx *mtx);
void mtxApplyAffineTransformInPlace(Mtx *matrix1, Mtx *matrix2);
void mtxApplyAffineTransform(Mtx *arg0, Mtx *arg1, Mtx *dst);
void mtxFrustum(Mtx *m, float l, float r, float b, float t, float n, float f, float scale);
void mtxPerspective(Mtx *mtx, float fovy, float aspect, float near, float far, float scale);
void mtxLookAtReflect(Mtx *mtx, LookAt *l, float xEye, float yEye, float zEye, float xAt,  float yAt,  float zAt, float xUp,  float yUp,  float zUp);
void mtx3Copy(float src[3][3], float dst[3][3]);
void mtx4Copy(Mtx *src, Mtx *dst);
void mtxScale3x4(float arg0, Mtx *arg1);
void mtxScaleRotationOnly(float scale, Mtx *arg1);
void mtx3ToMtx4(float src[3][3], Mtx *dst);
void mtx4ToMtx3(Mtx *src, float dst[3][3]);
void mtx3x3TransposeMulInPlace(float mtx1[3][3], float mtx2[3][3]);
void mtx3x3TransposeMul(float mtx1[3][3], float mtx2[3][3], float dst[3][3]);
void mtx3LinearTransform(float arg0[3][3], float src[3], float dest[3]);
void mtx00016208(float mtx[3][3], struct coord *coord);
void mtx4LoadYRotationWithTranslation(struct coord *pos, float radians, Mtx *mtx);
void mtx4LoadXRotation(float radians, Mtx *mtx);
void mtx4LoadYRotation(float angle, Mtx *mtx);
void mtx4LoadZRotation(float radians, Mtx *mtx);
void mtx4LoadRotation(struct coord *src, Mtx *dest);
void mtx4GetRotation(Mtx *mtx, struct coord *dst);
void mtx4LoadRotationAndTranslation(struct coord *pos, struct coord *rot, Mtx *mtx);
void mtx4LoadTranslation(struct coord *pos, Mtx *mtx);
void mtx00016710(float mult, Mtx *mtx);
void mtxBuildCameraMatrix(Mtx *mtx, float posx, float posy, float posz, float lookx, float looky, float lookz, float upx, float upy, float upz);
void mtxBuildLookAtMatrixF(Mtx *mtx, float posx, float posy, float posz, float lookx, float looky, float lookz, float upx, float upy, float upz);
void mtxBuildLookAtMatrix2F(Mtx *mtx, float posx, float posy, float posz, float lookx, float looky, float lookz, float upx, float upy, float upz);
void mtxBuildLookAtFromTarget(Mtx *mtx, float posx, float posy, float posz, float lookx, float looky, float lookz, float upx, float upy, float upz);
void mtxBuildFacingMatrix(Mtx *mtx, float angle, float x, float y, float z);
void mtx4Align(Mtx *mtx, float radians, float x, float y, float z);
void mtx4LoadRotationFrom(Mtx *src, Mtx *dst);
void mtxNormalizeRotationMatrix(Mtx *src, Mtx *dst);
void mtxInvertRigidBodyMatrix(Mtx *arg0, Mtx *arg1);
void mtxInvertAffine(Mtx *arg0, Mtx *arg1);
void mtxFullInverse4x4(float arg0[4][4], float arg1[4][4]);
void mtxAdjugate4x4(float arg0[4][4], float arg1[4][4]);
float mtxDet4x4(float arg0[4][4]);
float mtxDet3x3(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, float arg6, float arg7, float arg8);
float mtxDet2x2(float arg0, float arg1, float arg2, float arg3);