#pragma once

#include "data.h"
#include "types.h"

uint32_t pakGetBlockSize(int8_t device);
uint32_t pakAlign(int8_t device, uint32_t size);
int pakGetAlignedFileLenByBodyLen(int8_t device, uint32_t bodylen);
uint32_t pakGetBodyLenByFileLen(uint32_t filelen);
uint32_t pakGenerateSerial(int8_t device);
bool mempakIsOkay(int8_t device);
int pakGetFileIdsByType(int8_t device, uint32_t filetype, uint32_t *fileids);
int pak0f1167d8(int8_t device);
int pakReadBodyAtGuid(int8_t device, int fileid, uint8_t *body, int arg3);
int pakSaveAtGuid(int8_t device, int fileid, int filetype, uint8_t *body, int *outfileid, uint8_t *olddata);
bool pakDeleteFile(int8_t device, int fileid);
PakErr1 pakDeleteGameNote(int8_t device, uint16_t company_code, uint32_t game_code, char *game_name, char *ext_name);
PakErr1 pak0f1168c4(int8_t device, struct pakdata **arg1);
int pakGetType(int8_t device);
int pakGetSerial(int8_t device);
void pak0f116994(void);
void pak0f1169c8(int8_t device, bool tick);
bool mempakIsReady(int8_t device);
bool mempakIsReadyOrFull(int8_t device);
uint16_t _pakGetSerial(int8_t device);
uint32_t _pakGetType(int8_t device);
void pakSetState(int8_t device, int value);
int pak0f116df0(int8_t device, struct pakdata **arg1);
int _pakDeleteGameNote(int8_t device, uint16_t company_code, uint32_t game_code, char *game_name, char *ext_name);
int _pakDeleteFile(int8_t device, int fileid);
int pakGetPlugCount(int8_t device);
uint32_t pakGetMaxFileSize(int8_t device);
int pakGetBodyLenByType(int8_t device, uint32_t filetype);
bool pakRetrieveBlockFromCache(int8_t device, uint32_t offset, uint8_t *dst);
PakErr2 pakReadHeaderAtOffset(int8_t device, uint32_t offset, struct pakfileheader *header);
int _pakSaveAtGuid(int8_t device, int fileid, int filetype, uint8_t *newdata, int *outfileid, uint8_t *olddata);
PakErr1 pakInitPak(OSPfs *pfs, int channel, int *arg3);
PakErr1 _pakReadWriteBlock(OSPfs *pfs, int file_no, uint8_t flag, uint32_t address, uint32_t len, uint8_t *buffer);
PakErr1 pakQueryNumNotes(OSPfs *pfs, int *max_files, int *files_used);
PakErr1 pakQueryNumFreeBytes(OSPfs *pfs, int *bytes_not_used);
PakErr1 pakQueryNoteState(OSPfs *pfs, int file_no, OSPfsState *note);
PakErr1 pakAllocateNote(OSPfs *pfs, uint16_t company_code, uint32_t game_code, char *game_name, char *ext_name, int size, int *file_no);
PakErr1 pakDeleteGameNote3(OSPfs *pfs, uint16_t company_code, uint32_t game_code, char *game_name, char *ext_name);
PakErr1 pakFindNote(OSPfs *pfs, uint16_t company_code, uint32_t game_code, char *game_name, char *ext_name, int *file_no);
PakErr1 _pakResizeNote(OSPfs *pfs, uint16_t company_code, uint32_t game_code, uint8_t *game_name, uint8_t *ext_name, uint32_t numbytes);
int pakGetPdNumPages(int8_t device);
uint32_t pakGetPdNumBytes(int8_t device);
int pakQueryNumFreePages(int8_t device);
bool pakResizeNote(int8_t device, int numpages);
uint32_t pak0f118674(int8_t device, uint32_t filetype, int *outfileid);
void paksInit(void);
void pakCalculateChecksum(uint8_t *arg0, uint8_t *arg1, uint16_t *arg2);
int _pakReadBodyAtGuid(int8_t device, int fileid, uint8_t *body, int arg3);
int _pakGetFileIdsByType(int8_t device, uint32_t filetype, uint32_t *fileids);
int pakCheckFileCanFitInNote(int8_t device, int filetype, int *numspaces);
uint32_t pak0f119298(int8_t device);
int pakFindFile(int8_t device, uint32_t fileid, struct pakfileheader *header);
bool pakWriteBlankFile(int8_t device, uint32_t offset, struct pakfileheader *header);
bool pakRepairAsBlank(int8_t device, uint32_t *offset, struct pakfileheader *header);
int pakRepairFilesystem(int8_t device);
bool pakCreateInitialFiles(int8_t device);
int pakFindMaxFileId(int8_t device);
void pakMergeBlanks(int8_t device);
void pakSetFeatures(int8_t device, uint8_t features, uint32_t line, char *file);
void pakSetDefaults(int8_t arg0);
PakErr1 pakReadWriteBlock(int8_t device, OSPfs *pfs, int file_no, uint8_t flag, uint32_t address, uint32_t len, uint8_t *buffer);
bool pakQueryTotalUsage(int8_t device);
void pakQueryPdSize(int8_t device);
bool mempakPrepare(int8_t device);
bool pakProbe(int8_t device);
void pakWipe(int8_t device, uint32_t blocknumstart, uint32_t blocknumend);
void pakSaveHeaderToCache(int8_t device, int blocknum, struct pakfileheader *header);
bool pakRetrieveHeaderFromCache(int8_t device, int blocknum, struct pakfileheader *header);
int pakCreateFilesystem(int8_t device);
bool pakGetFilesystemLength(int8_t device, uint32_t *outlen);
int pak0f11b86c(int8_t device, uint32_t offset, uint8_t *data, struct pakfileheader *header, int arg4);
bool pakReplaceFileAtOffsetWithBlank(int8_t device, uint32_t offset);
int pakWriteFileAtOffset(int8_t device, uint32_t offset, uint32_t filetype, uint8_t *newdata, int bodylen, int *outfileid, uint8_t *olddata, uint32_t fileid, uint32_t generation);
bool pakRepair(int8_t device);
bool pakHandleResult(int err1, int8_t device, bool arg2, uint32_t line);
void paksTick(void);
void pak0f11c6d0(void);
void pakExecuteDebugOperations(void);
void pakCheckPlugged(void);
void gbpakHandleError(uint32_t arg0);
void pakRumble(int device, float numsecs, int onduration, int offduration);
void paksStop(bool disablepolling);
void pakDisableRumbleForPlayer(int8_t playernum);
void pakEnableRumbleForPlayer(int8_t playernum);
void pakDisableRumbleForAllPlayers(void);
void pakEnableRumbleForAllPlayers(void);
void pakTickState(int8_t device);
void pakProbeEeprom(void);
PakErr1 pakReadEeprom(uint8_t address, uint8_t *buffer, uint32_t len);
PakErr1 pakWriteEeprom(uint8_t address, uint8_t *buffer, uint32_t len);
void pakSetBitflag(int flagnum, uint8_t *bitstream, bool set);
bool pakHasBitflag(uint32_t flagnum, uint8_t *stream);
void pakClearAllBitflags(uint8_t *flags);
void pakN64FontCodeToAscii(char *src, char *dst, int len);
int8_t pakFindBySerial(int deviceserial);
bool gbpakIsAnyPerfectDark(void);