#pragma once

#include "data.h"
#include "types.h"

float playerChooseSpawnLocation(float chrradius, struct coord *dstpos, RoomNum *dstrooms, struct prop *prop, int16_t *spawnpads, int numspawnpads);
float playerChooseGeneralSpawnLocation(float chrradius, struct coord *pos, RoomNum *rooms, struct prop *prop);
void playerStartNewLife(void);
void playerLoadDefaults(void);
bool playerSpawnAnti(struct chrdata *hostchr, bool force);
void playerSpawn(void);
void playerResetBond(struct playerjo *pb, struct coord *pos);
void playersTickAllChrBodies(void);
void playerChooseBodyAndHead(int *bodynum, int *headnum, bool *arg2);
void playerTickChrBody(void);
void playerRemoveChrBody(void);
void playerTickMpSwirl(void);
void playerExecutePreparedWarp(void);
void playerStartCutscene(int16_t anim_id);
void playerReorientForCutsceneStop(int tweenduration60);
void playerTickCutscene(bool arg0);
float playerGetCutsceneBlurFrac(void);
void playerClampGunZoomFovY(int playernum);
void playerSetZoomFovY(float fovy, float timemax);
float playerGetZoomFovY(void);
void playerTweenFovY(float targetfovy);
float playerGetTeleportFovY(void);
void playerUpdateZoom(void);
void playerStopAudioForPause(void);
void playerTickPauseMenu(void);
void playerPause(int root);
void playerUnpause(void);
Gfx *player0f0baf84(Gfx *gdl);
Gfx *playerDrawFade(Gfx *gdl, uint32_t r, uint32_t g, uint32_t b, float frac);
Gfx *playerDrawStoredFade(Gfx *gdl);
void playerUpdateColourScreenProperties(void);
void playerTickChrFade(void);
void playerDisplayHealth(void);
void playerTickDamageAndHealth(void);
void playerDisplayDamage(void);
Gfx *playerRenderHealthBar(Gfx *gdl);
void playerSurroundWithExplosions(int arg0);
void playerTickExplode(void);
int16_t playerGetFbWidth(void);
int16_t playerGetFbHeight(void);
bool playerHasSharedViewport(void);
int16_t playerGetViewportWidth(void);
int16_t playerGetViewportLeft(void);
int16_t playerGetViewportHeight(void);
int16_t playerGetViewportTop(void);
int32_t playerGetViewportWidthReal(void);
int32_t playerGetViewportLeftReal(void);
int32_t playerGetViewportHeightReal(void);
int32_t playerGetViewportTopReal(void);
float playerGetAspect(void);
void playerUpdateShake(void);
void playerTickTeleport(float *arg0);
void playerConfigureVi(void);
void playerTick();
void playerAllocateMatrices(struct coord *cam_pos, struct coord *cam_look, struct coord *cam_up);
Gfx *playerUpdateShootRot(Gfx *gdl);
void playerDisplayShield(void);
Gfx *playerRenderShield(Gfx *gdl);
Gfx *playerRenderHud(Gfx *gdl);
void playerDie(bool force);
void playerDieByShooter(uint32_t shooter, bool force);
void playerCheckIfShotInBack(int attackerplayernum, float x, float z);
float playerGetHealthBarHeightFrac(void);
void playerFindAndSetCameraRoom(struct coord *pos, struct coord *up, struct coord *look, struct coord *pos2, RoomNum *rooms);
void playerSetCamFromMemCam(struct coord *pos, struct coord *up, struct coord *look, struct coord *memcampos, int memcamroom);
void playerUpdateCameraRoom(struct coord *pos, struct coord *up, struct coord *look);
void playersClearMemCamRoom(void);
void playerSetPerimEnabled(struct prop *prop, bool enable);
bool playerUpdateGeometry(struct prop *prop, uint8_t **start, uint8_t **end);
void playerUpdatePerimInfo(void);
void playerGetBbox(struct prop *prop, float *radius, float *ymax, float *ymin);
float playerGetHealthFrac(void);
float playerGetShieldFrac(void);
void playerSetShieldFrac(float frac);
int playerGetMissionTime(void);
int playerTickBeams(struct prop *prop);
int playerTickThirdPerson(struct prop *prop);
void playerChooseThirdPersonAnimation(struct chrdata *chr, int crouchpos, float speedsideways, float speedforwards, float speedtheta, float *angleoffset, struct attackanimconfig **animcfg);
Gfx *playerRender(struct prop *prop, Gfx *gdl, bool xlupass);
void player0f0c3320(Mtx *matrices, int count);
void playerSetTickMode(int tickmode);
void playersBeginMpSwirl(void);
void player0f0b9a20(void);
void playerEndCutscene(void);
void playerPrepareWarpType1(int16_t pad_id);
void playerPrepareWarpType2(struct warpparams *cmd, bool hasdir, int arg2);
void playerPrepareWarpType3(float posangle, float rotangle, float range, float height1, float height2, int padnum);
void playerStartCutscene2(void);
void playerSetFadeColour(int r, int g, int b, float a);
void playerAdjustFade(float maxfadetime, int r, int g, int b, float frac);
void playerSetFadeFrac(float maxfadetime, float frac);
bool playerIsFadeComplete(void);
void playerStartChrFade(float duration60, float targetfrac);
void playerAutoWalk(int16_t aimpad, uint8_t walkspeed, uint8_t turnspeed, uint8_t lookup, uint8_t dist);
void playerLaunchSlayerRocket(struct weaponobj *rocket);
void playerSetGlobalDrawWorldOffset(int room);
bool playerIsHealthVisible(void);
void playerSetCameraMode(int mode);
void playerSetCamPropertiesWithRoom(struct coord *pos, struct coord *up, struct coord *look, int room);
void playerSetCamPropertiesWithoutRoom(struct coord *pos, struct coord *up, struct coord *look, int room);
void playerSetCamProperties(struct coord *pos, struct coord *up, struct coord *look, int room);
void playerClearMemCamRoom(void);
Gfx *playerDrawCutsceneRects(Gfx *gdl);