#pragma once

#include "data.h"
#include "types.h"

extern struct prop *g_EmbedProp;
extern int g_EmbedHitPart;
extern float g_CctvWaitScale;
extern float g_CctvDamageRxScale;
extern float g_AutogunAccuracyScale;
extern float g_AutogunDamageTxScale;
extern float g_AutogunDamageRxScale;
extern struct beam *g_ThrownLaptopBeams;

void alarmActivate(void);
void alarmDeactivate(void);
bool alarmIsActive(void);
float countdownTimerGetValue60(void);
bool countdownTimerIsVisible(void);
bool countdownTimerIsRunning(void);
void countdownTimerSetRunning(bool running);
void countdownTimerSetValue60(float value);
void countdownTimerSetVisible(uint32_t reason, bool visible);
void countdownTimerTick(void);
bool doorCallLift(struct prop *doorprop, bool allowclose);
bool doorIsPadlockFree(struct doorobj *door);
bool objCanPickupFromSafe(struct defaultobj *obj);
void objUpdateLinkedScenery(struct defaultobj *obj, struct prop *prop);
float objGetLocalXMin(struct modelrodata_bbox *bbox);
float objGetLocalXMax(struct modelrodata_bbox *bbox);
float objGetLocalYMin(struct modelrodata_bbox *bbox);
float objGetLocalYMax(struct modelrodata_bbox *bbox);
float objGetLocalZMin(struct modelrodata_bbox *bbox);
float objGetLocalZMax(struct modelrodata_bbox *bbox);
float objGetRotatedLocalXMinByMtx4(struct modelrodata_bbox *bbox, Mtx *mtx);
float objGetRotatedLocalXMaxByMtx4(struct modelrodata_bbox *bbox, Mtx *mtx);
float objGetRotatedLocalYMinByMtx4(struct modelrodata_bbox *bbox, Mtx *mtx);
float objGetRotatedLocalYMaxByMtx4(struct modelrodata_bbox *bbox, Mtx *mtx);
float objGetRotatedLocalZMinByMtx4(struct modelrodata_bbox *bbox, Mtx *mtx);
float objGetRotatedLocalZMaxByMtx4(struct modelrodata_bbox *bbox, Mtx *mtx);
float objGetRotatedLocalXMinByMtx3(struct modelrodata_bbox *bbox, float realrot[3][3]);
float objGetRotatedLocalXMaxByMtx3(struct modelrodata_bbox *bbox, float realrot[3][3]);
float objGetRotatedLocalYMinByMtx3(struct modelrodata_bbox *bbox, float realrot[3][3]);
float objGetRotatedLocalYMaxByMtx3(struct modelrodata_bbox *bbox, float realrot[3][3]);
float objGetRotatedLocalZMinByMtx3(struct modelrodata_bbox *bbox, float realrot[3][3]);
float objGetRotatedLocalZMaxByMtx3(struct modelrodata_bbox *bbox, float realrot[3][3]);
float objGetRotatedLocalMin(struct modelrodata_bbox *bbox, float arg1, float arg2, float arg3);
float objGetRotatedLocalMax(struct modelrodata_bbox *bbox, float arg1, float arg2, float arg3);
int objCalculateGeoBlockVertices(float xmin, float xmax, float ymin, float ymax, float zmin, float zmax, Mtx *mtx, struct geoblock *block);
void objCalculateGeoBlockFromBboxAndMtx(struct modelrodata_bbox *bbox, Mtx *mtx, struct geoblock *block);
void objCalculateGeoBlockFromNode19Data(struct modelrodata_type19 *rodata19, struct modelrodata_bbox *bbox, Mtx *mtx, struct geoblock *block);
bool func0f0677ac(struct coord *coord, struct coord *arg1, struct coord *pos, struct coord *normal, struct coord *up, struct coord *look, float xmin, float xmax, float ymin, float ymax, float zmin, float zmax);
bool func0f0678f8(struct coord *coord, struct coord *arg1, int padnum);
bool func0f06797c(struct coord *coord, float arg1, int padnum);
bool objTestModelHit(struct model *model, float *max, float *min, float arg3[2], float arg4[2]);
void objFindBBOnAxis(struct model *model, float *max, float *min, int axis);
void func0f067d88(struct model *model, float *arg1, float *arg2, float *arg3, float *arg4);
bool modelGetScreenCoords2(struct model *model, float *x2, float *x1, float *y2, float *y1);
bool modelGetScreenCoords(struct model *model, float *x2, float *x1, float *y2, float *y1);
void func0f06803c(struct coord *arg0, float *arg1, float *arg2, float *arg3, float *arg4);
struct defaultobj *objFindByPadNum(int padnum);
struct defaultobj *objFindByPos(struct coord *pos, RoomNum *rooms);
void projectileFree(struct projectile *projectile);
void projectilesUnrefOwner(struct prop *owner);
void projectileReset(struct projectile *projectile);
struct projectile *projectileAllocate(void);
void projectileManage(struct prop *prop);
void projectileSetSticky(struct prop *prop);
void embedmentFree(struct embedment *embedment);
struct embedment *embedmentAllocate(void);
int objGetShotsTaken(struct defaultobj *obj);
int objGetDestroyedLevel(struct defaultobj *obj);
struct modelnode *func0f0687e4(struct model *model);
struct modelnode *modeldefFindBboxNode(struct modeldef *modeldef);
struct modelrodata_bbox *modeldefFindBboxRodata(struct modeldef *modeldef);
struct modelnode *modelFindBboxNode(struct model *model);
struct modelrodata_bbox *modelFindBboxRodata(struct model *model);
struct modelnode *objFindBboxNode(struct defaultobj *obj);
struct modelrodata_bbox *objFindBboxRodata(struct defaultobj *obj);
int objGetAverageBrightnessInRooms(RoomNum *rooms, int arg1);
int door0f068c04(struct prop *prop, int *arg1, int *arg2);
int func0f068fc8(struct prop *prop, bool arg1);
void propCalculateShadeColour(struct prop *prop, uint8_t *nextcol, uint16_t floorcol);
void propCalculateShadeInfo(struct prop *prop, uint8_t *nextcol, uint16_t floorcol);
void colourTween(uint8_t *col, uint8_t *nextcol);
void objMergeColourFracs(int *colour, int shademode, float fracs[4]);
void func0f069850(struct defaultobj *obj, struct coord *pos, float rot[3][3], struct geocyl *cyl);
void func0f069b4c(struct defaultobj *obj);
void func0f069c1c(struct defaultobj *obj);
void func0f069c70(struct defaultobj *obj, bool arg1, bool arg2);
void objInitToggleNodes(struct defaultobj *obj);
void objCreateOneDebris(struct defaultobj *obj, int partindex, struct prop *prop);
void objCreateDebris(struct defaultobj *obj, struct prop *prop);
struct prop *objInit(struct defaultobj *obj, struct modeldef *modeldef, struct prop *prop, struct model *model);
struct prop *objInitWithModelDef(struct defaultobj *obj, struct modeldef *modeldef);
struct prop *objInitWithAutoModel(struct defaultobj *obj);
void func0f06a580(struct defaultobj *obj, struct coord *pos, Mtx *matrix, RoomNum *rooms);
float objGetPlacementYOffset(struct defaultobj *obj);
void func0f06a730(struct defaultobj *obj, struct coord *arg1, Mtx *matrix, RoomNum *rooms, struct coord *arg4);
void objPlaceObjectAligned(struct defaultobj *obj, struct coord *arg1, Mtx *matrix, RoomNum *rooms, struct coord *impactPoint);
void objFreeProjectile(struct defaultobj *obj);
void objFreeEmbedmentOrProjectile(struct prop *prop);
void objFree(struct defaultobj *obj, bool freeprop, bool canregen);
void objFreePermanently(struct defaultobj *obj, bool freeprop);
float objGetRadius(struct defaultobj *obj);
bool projectileTryEmbedOnProp(struct prop *targetProp, struct coord *rayStart, struct coord *rayEnd, struct coord *rayDir, struct coord *outHitPos, struct coord *outHitNormal, float *closestHitDist);
bool projectileTestEmbedComplex(struct defaultobj *obj, struct coord *arg1, struct coord *arg2, struct coord *arg3, float arg4, struct coord *arg5, struct coord *arg6, struct coord *arg7, struct coord *arg8, float *arg9);
bool func0f06bea0(struct model *model, struct modelnode *arg1, struct modelnode *arg2, struct coord *arg3, struct coord *arg4, void *arg5, float *arg6, struct modelnode **arg7, int *hitpart, int *arg9, struct modelnode **arg10);
bool projectileTryEmbedOnChr(struct chrdata *chr, struct coord *start, struct coord *end, struct coord *dir, float maxdist, struct coord *rayStart, struct coord *rayDir, struct coord *outPos, struct coord *outNormal, float *closestDist);
bool projectileFindCollidingProp(struct prop *prop, struct coord *pos, struct coord *arg2, uint32_t cdtypes, struct coord *arg4, struct coord *arg5, RoomNum *rooms);
int func0f06cd00(struct defaultobj *obj, struct coord *pos, struct coord *arg2, struct coord *arg3);
bool projectileTryMove(struct defaultobj *obj, struct coord *arg1, struct coord *arg2, struct coord *arg3);
void applySpeed(float *distdone, float maxdist, float *speed, float accel, float decel, float maxspeed);
void applyRotation(float *angle, float maxrot, float *speed, float accel, float decel, float maxspeed);
void projectileFall(struct defaultobj *obj, float mtx[3][3]);
void knifePlayWooshSound(struct defaultobj *obj);
void objLand2(struct defaultobj *obj, struct coord *arg1, struct coord *arg2);
void boltLand(struct weaponobj *weapon, struct coord *arg1);
void knifeLand(struct defaultobj *obj, struct coord *arg1, struct coord *arg2);
bool objEmbed(struct prop *prop, struct prop *parent, struct model *model, struct modelnode *node);
void objLand(struct prop *prop, struct coord *arg1, struct coord *arg2, bool *embedded);
bool propExplode(struct prop *prop, int explosiontype);
void ammocrateTick(struct prop *ammocrate);
void weaponTick(struct prop *weapon);
void propTickWeaponsAndAmmoCrates(struct prop *prop, bool fulltick);
void objDropRecursively(struct prop *prop, bool arg1);
void propClearVisAndTickChildren(struct prop *prop, bool fulltick);
void func0f07079c(struct prop *prop, bool fulltick);
int glassCalculateOpacity(struct coord *pos, float opadist, float maxopacity, float minopacity);
void func0f070a1c(struct modelrodata_bbox *bbox, float realrot[3][3], struct coord *pos, struct coord *vertices);
void func0f070bd0(struct modelrodata_type19 *rodata, float realrot[3][3], struct coord *pos, struct coord *vertices);
void func0f070ca0(struct defaultobj *obj, struct geotilef *tile, uint32_t flags, struct modelrodata_bbox *bbox, struct modelrodata_type19 *rodata);
void liftActivate(struct prop *prop, uint8_t liftnum);
struct prop *liftFindByPad(int16_t padnum);
float liftGetY(struct liftobj *lift);
void liftUpdateTiles(struct liftobj *lift, bool stationary);
void liftGoToStop(struct liftobj *lift, int stopnum);
float objGetHovBobOffsetY(struct defaultobj *obj);
void hovUpdateGround(struct defaultobj *obj, struct hov *hov, struct coord *pos, RoomNum *rooms, float matrix[3][3]);
void hovTick(struct defaultobj *obj, struct hov *hov);
int objIsHoverpropOrBike(struct defaultobj *obj);
float hoverpropGetTurnAngle(struct defaultobj *obj);
void hoverpropSetTurnAngle(struct defaultobj *obj, float angle);
int func0f072144(struct defaultobj *obj, struct coord *arg1, float arg2, bool arg3);
void hovercarFindNextPath(struct hovercarobj *hovercar);
void hovercarStartNextPath(struct hovercarobj *hovercar);
void hovercarIncrementStep(struct hovercarobj *hovercar);
float objCollide(struct defaultobj *obj, struct coord *arg1, float arg2);
void hoverbikeUpdateMovement(struct hoverbikeobj *hoverbike, float arg1, float arg2, float arg3);
void platformDisplaceProps2(struct prop *platform, Mtx *arg1);
bool rocketTickFbw(struct weaponobj *rocket);
int projectileLaunch(struct defaultobj *obj, struct projectile *projectile, struct coord *arg2, struct coord *arg3);
int projectileTick(struct defaultobj *obj, bool *embedded);
void doorTick(struct prop *doorprop);
void doorUpdatePortalIfWindowed(struct prop *door, int playercount);
void doorInitMatrices(struct prop *door);
void platformDisplaceProps(struct prop *platform, int16_t *propnums, struct coord *prevpos, struct coord *newpos);
void liftTick(struct prop *lift);
void escastepTick(struct prop *escalator);
void cctvTick(struct prop *camera);
void cctvInitMatrices(struct prop *cctv, Mtx *mtx);
void fanTick(struct prop *fan);
void fanUpdateModel(struct prop *fan);
void autogunTick(struct prop *autogun);
void autogunInitMatrices(struct prop *autogun, Mtx *mtx);
void autogunTickShoot(struct prop *autogun);
void chopperInitMatrices(struct prop *chopper);
struct chopperobj *chopperFromHovercar(struct chopperobj *obj);
bool chopperCheckTargetInFov(struct chopperobj *hovercar, uint8_t param_2);
bool chopperCheckTargetInSight(struct chopperobj *obj);
void chopperSetTarget(struct chopperobj *obj, uint32_t chrnum);
bool chopperAttack(struct chopperobj *obj);
bool chopperStop(struct chopperobj *obj);
bool chopperSetArmed(struct chopperobj *obj, bool armed);
void chopperRestartTimer(struct chopperobj *obj);
float chopperGetTimer(struct chopperobj *heli);
void chopperSetMaxDamage(struct chopperobj *obj, uint16_t health);
float func0f07b164(struct coord *pos1, struct coord *pos2, struct coord *pos3, struct coord *result);
void chopperFireRocket(struct chopperobj *chopper, bool side);
void chopperIncrementBarrel(struct prop *prop, bool firing);
void chopperIncrementMovement(struct prop *prop, float goalroty, float goalrotx, struct coord *dir, bool firing);
void chopperTickFall(struct prop *chopper);
void chopperTickIdle(struct prop *chopper);
void chopperTickPatrol(struct prop *chopper);
void chopperTickCombat(struct prop *chopper);
void hovercarTick(struct prop *hovercar);
void hoverpropTick(struct prop *hoverprop, bool arg1);
void hoverbikeTick(struct prop *hoverbike, bool arg1);
void dropshipUpdateInterior(struct prop *prop);
void glassUpdatePortal(struct prop *glass, int playercount, bool *arg2);
void weaponInitMatrices(struct prop *weapon);
void hangingmonitorInitMatrices(struct prop *hangingmonitors);
void objInitMatrices(struct prop *prop);
uint32_t objTick(struct prop *prop);
int objTickPlayer(struct prop *prop);
Gfx *propsRenderBeams(Gfx *gdl);
void tvscreenSetCmdlist(struct tvscreen *screen, uint32_t *cmdlist);
void tvscreenSetImageByNum(struct tvscreen *screen, int imagenum);
void tvscreenSetTexture(struct tvscreen *screen, int texturenum);
Gfx *tvscreenRender(struct model *model, struct modelnode *node, struct tvscreen *screen, Gfx *gdl, int arg4, int arg5);
void objRenderProp(struct prop *prop, struct modelrenderdata *renderdata, bool xlupass);
Gfx *gfxRenderRadialShadow(Gfx *gdl, float x, float y, float z, float angle, float radius, uint32_t colour);
Gfx *objRenderShadow(struct defaultobj *obj, Gfx *gdl);
Gfx *objRender(struct prop *prop, Gfx *gdl, bool xlupass);
bool modelIsNodeNotTvscreen(struct modeldef *modeldef, struct modelnode *node);
void objDeform(struct defaultobj *obj, int level);
void objBounce(struct defaultobj *obj, struct coord *gundir2d);
void objSetDropped(struct prop *prop, uint32_t droptype);
void objApplyMomentum(struct defaultobj *obj, struct coord *speed, float rotation, bool addspeed, bool addrotation);
void func0f082e84(struct defaultobj *obj, struct coord *pos, struct coord *dir, struct coord *tween, bool addrotation);
void objDetach(struct prop *prop);
bool objDrop(struct prop *prop, bool lazy);
void objFall(struct defaultobj *obj, int playernum);
void objDestroySupportedObjects(struct prop *prop, int playernum);
void objCheckDestroyed(struct defaultobj *obj, struct coord *pos, int playernum);
bool func0f084594(struct model *model, struct modelnode *node, struct coord *arg2, struct coord *arg3, struct hitthing *arg4, int *arg5, struct modelnode **arg6);
bool func0f0849dc(struct model *model, struct modelnode *nodearg, struct coord *arg2, struct coord *arg3, struct hitthing *hitthing, int *dstmtxindex, struct modelnode **dstnode);
uint32_t add43214321(uint32_t value);
void glassDestroy(struct defaultobj *obj);
void doorDestroyGlass(struct doorobj *door);
void func0f085050(struct prop *prop, float damage, struct coord *pos, int arg3, int playernum);
bool objIsMovablePickup(struct defaultobj *obj);
bool objIsMortal(struct defaultobj *obj);
void objTakeGunfire(struct defaultobj *obj, float damage, struct coord *pos, int weaponnum, int playernum);
void objDamage(struct defaultobj *obj, float damage, struct coord *pos, int weaponnum, int playernum);
void propTestModelHit(struct prop *prop, struct shotdata *shotdata);
void objTestHit(struct prop *prop, struct shotdata *shotdata);
void objHit(struct shotdata *shotdata, struct hit *hit);
uint32_t propobjGetCiTagId(struct prop *prop);
bool objIsHealthy(struct defaultobj *obj);
bool objTestForInteract(struct prop *prop);
bool currentPlayerTryMountHoverbike(struct prop *prop);
bool propobjInteract(struct prop *prop);
void objSetPerimEnabled(struct prop *prop, bool enable);
bool objUpdateGeometry(struct prop *prop, uint8_t **start, uint8_t **end);
void objGetBbox(struct prop *prop, float *radius, float *ymax, float *ymin);
void ammotypeGetPickedUpText(char *dst);
void ammotypeGetDeterminer(char *dst, int ammotype, int qty);
void ammotypeGetPickupName(char *dst, int ammotype, int qty);
void ammotypePlayPickupSound(uint32_t ammotype);
int propPlayPickupSound(struct prop *prop, int weapon);
void weaponPlayPickupSound(int weaponnum);
void ammotypeGetPickupMessage(char *dst, int ammotype, int qty);
void currentPlayerQueuePickupAmmoHudmsg(int ammotype, int pickupqty);
void ammoHandlePickup(int ammotype, int quantity, bool withsound, bool withhudmsg);
int ammocrateGetPickupAmmoQty(struct ammocrateobj *crate);
int weaponGetPickupAmmoQty(struct weaponobj *weapon);
void weaponGetPickupText(char *buffer, int weaponnum, bool dual);
void currentPlayerQueuePickupWeaponHudmsg(uint32_t weaponnum, bool dual);
int propPickupByPlayer(struct prop *prop, bool showhudmsg);
int objTestForPickup(struct prop *prop);
bool propGetScreenBoundsIfVisible(struct prop *prop, struct coord *arg1, float *arg2, float *arg3);
void modelFreeVertices(int vtxstoretype, struct model *model);
struct weaponobj *weaponCreate(bool musthaveprop, bool musthavemodel, struct modeldef *modeldef);
struct ammocrateobj *ammocrateAllocate(void);
struct defaultobj *debrisAllocate(void);
void playerActivateRemoteMineDetonator(int playernum);
struct weaponobj *weaponFindChildByWeaponNum(int weaponnum, struct prop *prop);
struct weaponobj *weaponFindLanded(int weaponnum);
void weaponRegisterProxy(struct weaponobj *weapon);
void weaponUnregisterProxy(struct weaponobj *weapon);
void coordTriggerProxies(struct coord *pos, bool arg1);
void chrsTriggerProxies(void);
void propweaponSetDual(struct weaponobj *weapon1, struct weaponobj *weapon2);
struct prop *func0f08adc8(struct weaponobj *weapon, struct modeldef *modeldef, struct prop *prop, struct model *model);
struct prop *func0f08ae0c(struct weaponobj *weapon, struct modeldef *modeldef);
bool chrEquipWeapon(struct weaponobj *weapon, struct chrdata *chr);
struct prop *func0f08b108(struct weaponobj *weapon, struct chrdata *chr, struct modeldef *modeldef, struct prop *prop, struct model *model);
void func0f08b208(struct weaponobj *weapon, struct chrdata *chr);
struct autogunobj *laptopDeploy(int modelnum, struct gset *gset, struct chrdata *chr);
struct weaponobj *weaponCreateProjectileFromGset(int modelnum, struct gset *gset, struct chrdata *chr);
struct weaponobj *weaponCreateProjectileFromWeaponNum(int modelnum, int weaponnum, struct chrdata *chr);
void weaponDeleteFromChr(struct chrdata *chr, int hand);
struct prop *weaponCreateForChr(struct chrdata *chr, int modelnum, int weaponnum, uint32_t flags, struct weaponobj *obj, struct modeldef *modeldef);
struct prop *chrGiveWeapon(struct chrdata *chr, int model, int weaponnum, uint32_t flags);
int weaponTestForPickup(struct prop *prop);
void weaponSetGunfireVisible(struct prop *prop, bool visible, RoomNum room);
bool weaponIsGunfireVisible(struct prop *prop);
int hatGetType(struct prop *prop);
bool doorIsUnlocked(struct prop *playerprop, struct prop *doorprop);
bool doorIsPosInRange(struct doorobj *door, struct coord *pos, float arg2, bool isbike);
bool doorIsObjInRange(struct doorobj *door, struct defaultobj *obj, bool isbike);
bool vectorIsInFrontOfDoor(struct doorobj *door, struct coord *vector);
bool doorIsRangeEmpty(struct doorobj *door);
void doorsCheckAutomatic(void);
void func0f08c424(struct doorobj *door, Mtx *matrix);
void doorGetBbox(struct doorobj *door, struct modelrodata_bbox *dst);
void doorUpdateTiles(struct doorobj *door);
void door0f08cb20(struct doorobj *door, Vtx *src, Vtx *dst, int numvertices);
void func0f08d3dc(struct doorobj *door);
void func0f08d460(struct doorobj *door);
void doorActivatePortal(struct doorobj *door);
void doorDeactivatePortal(struct doorobj *door);
struct prop *doorInit(struct doorobj *door, struct coord *pos, Mtx *mtx, RoomNum *rooms, struct coord *coord, struct coord *centre);
void doorPlayOpeningSound(int soundtype, struct prop *prop);
void doorPlayClosingSound(int soundtype, struct prop *prop);
void doorPlayOpenedSound(int soundtype, struct prop *prop);
void doorPlayClosedSound(int soundtype, struct prop *prop);
void doorStartOpen(struct doorobj *door);
void doorStartClose(struct doorobj *door);
uint32_t decodeXorAaaaaaaa(uint32_t value);
void doorFinishOpen(struct doorobj *door);
void doorFinishClose(struct doorobj *door);
void doorSetMode(struct doorobj *door, int newmode);
void doorsRequestMode(struct doorobj *door, int newmode);
int doorIsClosed(struct doorobj *door);
int doorIsOpen(struct doorobj *door);
int func0f08e5a8(RoomNum *rooms, struct screenbox *box);
//bool posIsInObjFadeDistance(struct coord *coord, float modelscale);
bool posShouldRenderForProp(struct prop *prop, struct coord *pos, float arg2, bool arg3);
void doorCreateSparks(struct doorobj *door);
bool doorCalcIntendedFrac(struct doorobj *door);
void doorsCalcFrac(struct doorobj *door);
float func0f08f538(float x, float y);
void door0f08f604(struct doorobj *door, float *arg1, float *arg2, float *arg3, float *arg4, bool altcoordsystem);
bool func0f08f968(struct doorobj *door, bool altcoordsystem);
bool doorTestForInteract(struct prop *prop);
void doorsActivate(struct prop *prop, bool allowliftclose);
bool posIsInFrontOfDoor(struct coord *pos, struct doorobj *door);
void doorsChooseSwingDirection(struct prop *chrprop, struct doorobj *door);
bool propdoorInteract(struct prop *doorprop);
void alarmStopAudio(void);
void gasReleaseFromPos(struct coord *pos);
void gasStopAudio(void);
bool gasIsActive(void);
void gasTick(void);
Gfx *countdownTimerRender(Gfx *gdl);
void alarmTick(void);
void func0f091030(void);
void currentPlayerDropAllItems(void);
void weaponCreateForPlayerDrop(int weaponnum);
void projectileCreate(struct prop *fromprop, struct fireslotthing *arg1, struct coord *pos, struct coord *direction, uint8_t weaponnum, struct prop *targetprop);
void objSetModelPartVisible(struct defaultobj *obj, int partnum, bool visible);