#ifndef IN_GAME_TRAINING_TRAINING_H
#define IN_GAME_TRAINING_TRAINING_H
#include <ultra64.h>
#include "data.h"
#include "types.h"

extern uint8_t g_FrIsValidWeapon;
extern int g_FrWeaponNum;
extern uint8_t g_ChrBioSlot;
extern uint8_t g_HtScenario;
extern uint8_t g_HangarBioSlot;
extern uint8_t g_DtSlot;

bool ciIsTourDone(void);
uint8_t ciGetFiringRangeScore(int weaponindex);
void frSaveScoreIfBest(int weaponindex, int difficulty);
uint8_t frIsWeaponFound(int weapon);
void frSetWeaponFound(int weaponnum);
int ciIsStageComplete(int stageindex);
bool frIsDeviceUnlocked(int weapon);
bool frIsWeaponAvailable(int weapon);
uint32_t frGetWeaponIndexByWeapon(uint32_t weaponnum);
uint32_t frGetWeaponScriptIndex(uint32_t weaponnum);
int frIsClassicWeaponUnlocked(uint32_t weapon);
int frGetSlot(void);
void frSetSlot(int slot);
uint32_t frGetWeaponBySlot(int slot);
int frGetNumWeaponsAvailable(void);
void frInitLighting(void);
void frRestoreLighting(void);
void frReset(void);
void *frLoadRomData(uint32_t len);
void frSetDifficulty(int difficulty);
uint32_t frGetDifficulty(void);
void frInitDefaults(void);
struct frdata *frGetData(void);
uint32_t frResolveFrPad(uint32_t arg0);
bool frIsDifficulty(uint32_t difficulties);
void frExecuteWeaponScript(int scriptindex);
void frSetTargetProps(void);
bool frTargetIsAtScriptStart(int targetnum);
char *frGetInstructionalText(uint32_t index);
void frExecuteHelpScript(void);
bool frExecuteTargetScript(int targetnum);
void frHideAllTargets(void);
void frInitTargets(void);
void frCloseAndLockDoor(void);
void frUnlockDoor(void);
void frLoadData(void);
uint32_t frInitAmmo(int weapon);
void frBeginSession(int weapon);
char *frGetWeaponDescription(void);
void frEndSession(bool hidetargets);
bool frWasTooInaccurate(void);
void frSetFailReason(int failreason);
void frSetCompleted(void);
bool frIsTargetOneHitExplodable(struct prop *prop);
float frGetTargetAngleToPos(struct coord *a, float angle, struct coord *b);
bool frIsTargetFacingPos(struct prop *prop, struct coord *pos);
struct prop *frChooseAutogunTarget(struct coord *autogunpos);
bool frIsAmmoWasted(void);
void frTick(void);
void func0f1a0924(struct prop *prop);
bool frChooseFarsightTarget(void);
int frIsInTraining(void);
void frCalculateHit(struct defaultobj *obj, struct coord *hitpos, float maulercharge);
void frIncrementNumShots(void);
bool ciIsChrBioUnlocked(uint32_t bodynum);
struct chrbio *ciGetChrBioByBodynum(uint32_t bodynum);
char *ciGetChrBioDescription(void);
int ciGetNumUnlockedChrBios(void);
int ciGetChrBioBodynumBySlot(int slot);
struct miscbio *ciGetMiscBio(int index);
bool ciIsMiscBioUnlocked(int index);
int ciGetNumUnlockedMiscBios(void);
int ciGetMiscBioIndexBySlot(int slot);
char *ciGetMiscBioDescription(void);
bool ciIsHangarBioAVehicle(int index);
struct hangarbio *ciGetHangarBio(int index);
bool ciIsHangarBioUnlocked(uint32_t bioindex);
int ciGetNumUnlockedLocationBios(void);
int ciGetNumUnlockedHangarBios(void);
int ciGetHangarBioIndexBySlot(int slot);
char *ciGetHangarBioDescription(void);
struct trainingdata *dtGetData(void);
void dtRestorePlayer(void);
void dtPushEndscreen(void);
void dtTick(void);
void dtInit(void);
void dtBegin(void);
void dtEnd(void);
bool dtIsAvailable(int deviceindex);
int dtGetNumAvailable(void);
int dtGetIndexBySlot(int wantindex);
uint32_t dtGetWeaponByDeviceIndex(int deviceindex);
uint32_t ciGetStageFlagByDeviceIndex(uint32_t deviceindex);
char *dtGetDescription(void);
char *dtGetTip1(void);
char *dtGetTip2(void);
struct trainingdata *getHoloTrainingData(void);
void htPushEndscreen(void);
void htTick(void);
void func0f1a2198(void);
void htBegin(void);
void htEnd(void);
bool htIsUnlocked(uint32_t value);
int htGetNumUnlocked(void);
int htGetIndexBySlot(int slot);
char *htGetName(int index);
uint32_t func0f1a25c0(int index);
char *htGetDescription(void);
char *htGetTip1(void);
char *htGetTip2(void);
void frGetGoalTargetsText(char *buffer);
void frGetGoalScoreText(char *buffer);
bool frGetMinAccuracy(char *buffer, float accuracy);
bool frGetHudMiddleSubtext(char *buffer);
bool frGetFeedback(char *score, char *zone);
Gfx *frRenderHudElement(Gfx *gdl, int x, int y, char *string1, char *string2, uint32_t colour, uint8_t alpha);

void frGetTargetsDestroyedValue(char *buffer);
void frGetScoreValue(char *buffer);
float frGetAccuracy(char *buffer);
bool frFormatTime(char *buffer);
Gfx *frRenderHud(Gfx *gdl);

#endif
