#ifndef _IN_BSS_H
#define _IN_BSS_H
#include <ultra64.h>
#include "constants.h"
#include "types.h"

extern uint8_t g_SchedSpecialArtifactIndexes[3];
extern int g_SchedWriteArtifactsIndex;
extern uint8_t *g_VmMarker;
extern uint32_t g_VmRamEnd;
extern uint32_t g_VmVirtualToPhysicalTableEnd;
extern AMAudioMgr g_AudioManager;
extern Mtx *g_CameraPerspectiveMtxF;
extern int g_SndMaxFxBusses;
extern struct seqinstance g_SeqInstances[3];
extern ALHeap g_SndHeap;
extern uint32_t var80095200;
extern struct g_vars g_Vars;
extern uint8_t **g_AnimFrameBytes;
extern uint8_t **g_AnimHeaderBytes;
extern union filedataptr g_TileFileData;
extern int g_TileNumRooms;
extern int32_t *g_TileRooms;
extern struct geoblock g_CdSavedBlock;
extern uint8_t g_RdpDramStack[1024];
extern N_ALSndPlayer var8009c2d0;
extern struct N_SpeakerType N_SpeakerType;
extern uint8_t var8009c344[2];
extern uint32_t var8009c3e0;
extern struct asistream *g_AsiStream;
extern struct mp3decfourbytes *var8009c640;
extern float *var8009c644;
extern float *var8009c6d8;
extern float *var8009c6dc;
extern uint32_t var8009ca84;
extern uint16_t *g_FrameBuffers[NUM_FRAMEBUFFERS];
extern uint8_t var8009caec;
extern uint8_t var8009caed;
extern uint8_t var8009caee;
extern uint8_t g_NVChrHighlight;
extern uint8_t g_NVChrBrightness;
extern struct prop *g_DangerousProps[12];
extern uint16_t *g_WallhitCountsPerRoom;
extern int g_WallhitsMax;
extern uint32_t g_WallhitsNumSettled;
extern uint32_t g_WallhitsNumFree;
extern uint32_t g_WallhitsNumUsed;
extern uint32_t g_WallhitsNumBloodSettled;
extern uint32_t g_WallhitsNumNonbloodSettled;
extern int g_MinPropWallhits;
extern uint32_t g_MaxPropWallhits;
extern int g_MinBgWallhitsPerRoom;
extern int g_MaxBgWallhitsPerRoom;
extern int g_WallhitsCriticalSpareLimit;
extern int g_WallhitsGoalSpareLimit;
extern float g_WallhitTargetBloodRatio;
extern int8_t *g_TitleModelBuffer;
extern int var8009ccc0[20];
extern int g_NumChrs;
extern int16_t *g_Chrnums;
extern int16_t *g_ChrIndexes;
extern int g_NumActiveHeadsPerGender;
extern int g_ActiveMaleHeads[8];
extern int g_ActiveFemaleHeads[8];
extern int16_t *g_RoomPropListChunkIndexes;
extern struct roomproplistchunk *g_RoomPropListChunks;
extern struct prop *g_InteractProp;
extern int var8009cdac;
extern int var8009cdb0;
extern struct weaponobj *g_Proxies[30];
extern int g_MaxWeaponSlots;
extern int g_MaxHatSlots;
extern int g_MaxAmmoCrates;
extern int g_MaxDebrisSlots;
extern int g_MaxProjectiles;
extern int g_MaxEmbedments;
extern struct weaponobj *g_WeaponSlots;
extern struct hatobj *g_HatSlots;
extern struct ammocrateobj *g_AmmoCrates;
extern struct defaultobj *g_DebrisSlots;
extern struct projectile *g_Projectiles;
extern struct embedment *g_Embedments;
extern struct model *g_EmbedModel;
extern struct modelnode *g_EmbedNode;
extern struct coord var8009ce78;
extern struct coord var8009ce88;
extern struct tvscreen var8009ce98;
extern struct tvscreen var8009cf10;
extern struct tvscreen var8009cf88;
extern struct stagesetup g_StageSetup;
extern uint8_t *g_GeCreditsData;
extern struct objective *g_Objectives[MAX_OBJECTIVES];
extern uint32_t g_ObjectiveStatuses[MAX_OBJECTIVES];
extern struct tag *g_TagsLinkedList;
extern struct briefingobj *g_BriefingObjs;
extern struct criteria_roomentered *g_RoomEnteredCriterias;
extern struct criteria_throwinroom *g_ThrowInRoomCriterias;
extern struct criteria_holograph *g_HolographCriterias;
extern struct sndstate *g_CasingAudioHandles[2];
extern int g_TimeToNextCasingSound; //Time until next casing audio sound is allowed to be made
extern struct sndstate *g_BgunAudioHandles[MAX_PLAYERS];
extern struct fireslot g_Fireslots[20];
extern struct casing g_Casings[20];
extern struct boltbeam g_BoltBeams[8];
extern struct lasersight g_LaserSights[MAX_PLAYERS];
extern struct model *g_ModelSlots;
extern struct anim *g_AnimSlots;
extern int g_ModelNumObjs;
extern int g_ModelNumChrs;
extern struct modelrwdatabinding *g_ModelRwdataBindings[3];
extern struct coord var8009dd20;
extern float var8009dd2c;
extern struct coord var8009dd30;
extern float var8009dd3c;
extern struct coord var8009dd40;
extern float var8009dd4c;
extern struct coord var8009dd50;
extern float var8009dd5c;
extern float var8009dd6c;
extern int g_DefaultWeapons[2];
extern int g_CutsceneCurAnimFrame60;
extern int16_t g_CutsceneAnimNum;
extern int g_CutsceneFrameOverrun240;
extern bool g_CutsceneSkipRequested;
extern float g_CutsceneCurTotalFrame60f;
extern int16_t g_SpawnPoints[];
extern int g_NumSpawnPoints;
extern int var8009de90;
extern int var8009de94;
extern int g_MenuProjectFromX;
extern int g_MenuProjectFromY;
extern uint8_t g_MpSelectedPlayersForStats[MAX_PLAYERS];
extern char g_CheatMarqueeString[];
extern uint8_t *g_BlurBuffer;
extern bool g_GamePaused;
extern struct briefing g_Briefing;
extern struct missionconfig g_MissionConfig;
extern struct menu g_Menus[MAX_PLAYERS];
extern struct menudata g_MenuData;
extern struct activemenu g_AmMenus[MAX_PLAYERS];
extern int g_AmIndex;
extern uint32_t g_CheatsActiveBank0;
extern uint32_t g_CheatsActiveBank1;
extern uint32_t g_CheatsEnabledBank0;
extern uint32_t g_CheatsEnabledBank1;
extern int g_FilemgrLastPakError;
extern struct gamefile g_GameFile;
extern struct fileguid g_GameFileGuid;
extern uint8_t g_AltTitleUnlocked;
extern uint8_t g_AltTitleEnabled;
extern struct padsfileheader *g_PadsFile;
extern uint16_t *g_PadOffsets;
extern uint16_t *g_CoverFlags;
extern int *g_CoverRooms;
extern struct covercandidate *g_CoverCandidates;
extern uint16_t g_NumSpecialCovers;
extern uint16_t *g_SpecialCoverNums;
extern struct pak g_Paks[5];
extern OSPfs g_Pfses[MAX_PLAYERS];
extern uint32_t g_SkyStageNum;
extern bool g_SkyLightningActive;
extern struct explosion *g_Explosions;
extern int g_MaxExplosions;
extern struct smoke *g_Smokes;
extern int g_MaxSmokes;
extern Mtx var800a3448;
extern Mtx var800a3488;
extern struct spark g_Sparks[100];
extern int g_NextSparkIndex;
extern struct sparkgroup g_SparkGroups[10];
extern int g_NextSparkGroupIndex;
extern uint8_t *var800a41a0;
extern struct wallhit *g_Wallhits;
extern struct wallhit *g_FreeWallhits;
extern struct wallhit *g_ActiveWallhits;
extern int g_MaxShards;
extern struct shard *g_Shards;
extern Gfx *var800a4634;
extern struct room *g_Rooms;
extern uint8_t *g_MpRoomVisibility;
extern struct bgroom *g_BgRooms;
extern struct bgportal *g_BgPortals;
extern struct portalmetric *g_PortalMetrics;
extern uint8_t *g_BgLightsFileData;
extern int16_t *g_RoomPortals;
extern struct bgsnake g_BgSnake;
extern float var800a6470[16 * 3];
extern struct var800a6538 var800a6538[16];
extern uint32_t g_BgRoomTestsDisabled;
extern struct screenbox g_BgCmdScreenBox;
extern struct screenbox g_PortalScreenBbox;
extern uint32_t g_BgCmdThrowing;
extern int g_BgNumLightsChecksum;
extern int g_BgLightsOffsetChecksum;
extern bool g_FogEnabled;
extern bool g_EnvHasTransparency;
extern struct distfadesettings *g_EnvDistFadeSettingsPtr;
extern uint8_t *g_RoomMtxAges;
extern RoomNum *g_RoomMtxLinkedRooms;
extern RoomNum *g_RoomMtxBaseRooms;
extern float *g_RoomMtxScales;
extern Mtxf *g_RoomMtxMatrices;
extern struct fileinfo g_FileInfo[NUM_FILES];
extern uint8_t *g_VtxBuffers[3];
extern uint8_t *g_GfxMemPos;
extern uint8_t g_GfxActiveBufferIndex;
extern int g_MusicStageNum;
extern struct musicevent g_MusicEventQueue[40];
extern struct seqchannel g_SeqChannels[3];
extern uint32_t g_AudioXReasonsActive[4];
extern int g_MusicXReasonMinDurations[4];
extern int g_MusicXReasonMaxDurations[4];
extern struct langbank g_LangBanks[29];
extern struct texture *g_Textures;
extern struct texpool g_TexSharedPool;
extern struct texcacheitem g_TexCacheItems[150];
extern int g_TexCacheCount;
extern uint8_t *g_TexBitstring;
extern uint32_t g_TexAccumValue;
extern int g_TexAccumNumBits;
extern int g_TexNumConfigs;
extern struct tex **g_TexWords;
extern struct textureconfig *g_TexWallhitConfigs;
extern Gfx *g_TexGdl1;
extern Gfx *g_TexGdl2;
extern struct texturepair *g_ExplosionTexturePairs;
extern struct textureconfig *g_TexBeamConfigs;
extern struct textureconfig *g_TexLaserConfigs;
extern struct textureconfig *g_TexGroup03Configs;
extern struct textureconfig *g_TexGeCrosshairConfigs;
extern struct textureconfig *g_TexShadowConfigs;
extern struct textureconfig *g_TexShieldConfigs;
extern struct textureconfig *g_TexShardConfigs;
extern struct textureconfig *g_TexScreenConfigs;
extern struct textureconfig *g_TexSkyWaterConfigs;
extern struct textureconfig *g_TexLightGlareConfigs;
extern struct textureconfig *g_TexSparkConfigs;
extern struct textureconfig *g_TexGeneralConfigs;
extern struct textureconfig *g_TexRadarConfigs;
extern struct textureconfig *g_TexStarsConfigs;
extern struct scenariodata g_ScenarioData;
extern struct chrdata *g_MpAllChrPtrs[MAX_MPCHRS];
extern struct mpchrconfig *g_MpAllChrConfigPtrs[MAX_MPCHRS];
extern int g_MpNumChrs;
extern struct mpbotconfig g_BotConfigsArray[MAX_BOTS];
extern uint8_t g_MpSimulantDifficultiesPerNumPlayers[MAX_BOTS][MAX_PLAYERS];
extern struct mpplayerconfig g_PlayerConfigsArray[MAX_MPPLAYERCONFIGS];
extern uint8_t g_AmBotCommands[9];
extern struct mpsetup g_MpSetup;
extern struct bossfile g_BossFile;
extern struct chrdata *g_MpBotChrPtrs[MAX_BOTS];
extern bool g_ValidGbcRomFound;

#endif
