#pragma once

#include <stdint.h>
#include "constants.h"
#include "types.h"

extern int g_SchedViModeToggle;
extern bool g_SchedViModesPending[NUM_GFXTASKS];
extern int g_ViShakeDirection;
extern int g_ViShakeIntensity;
extern int g_ViShakeTimer;
extern uint8_t g_LoadType;
extern bool g_MainIsEndscreen;
extern bool g_MainIsBooting;
extern bool g_SndDisabled;
extern uint16_t g_SfxVolume;
extern int g_SoundMode;
extern int g_SndNumPlaying;
extern struct audiorussmapping g_AudioRussMappings[];
extern struct audioconfig g_AudioConfigs[];
extern bool g_JoyPfsPollMasterEnabled;
extern int g_NumGlobalAilists;
extern int g_NumLvAilists;
extern bool g_ModelDistanceDisabled;
extern float g_ModelDistanceScale;
extern float g_ExtraBoundsDist;
extern bool g_ModelAnimMergingEnabled;
extern uint32_t g_NextAnimFrameIndex;
extern int16_t g_NumAnimations;
extern struct animtableentry *g_Anims;
extern uint8_t *g_AnimToHeaderSlot;
extern float *g_AnimAvgForwardPerFrame;
extern int g_AnimMaxBytesPerFrame;
extern int g_AnimMaxHeaderLength;
extern bool g_CdHasSavedBlock;
extern struct rdptask *g_RdpCurTask;
extern N_ALSndPlayer *g_SndPlayer;
extern int16_t n_eqpower[];
extern uint8_t *var8005f6f8;
extern uint8_t *var8005f6fc;
extern uint32_t g_MP3Init;
extern uint32_t var80060890;
extern char ldigs[];
extern char udigs[];
extern Gfx var80061380[];
extern Gfx var800613a0[];
extern float g_20SecIntervalFrac;
extern float g_Lv80SecIntervalFrac;
extern bool g_NbombsActive;
extern bool g_WeatherActive;
extern bool g_IsTitleDemo;
extern uint32_t g_TitleIdleTime60;
extern int g_TitleMode;
extern int g_TitleNextMode;
extern uint32_t g_TitleDelayedTimer;
extern int g_TitleDelayedMode;
extern int g_TitleTimer;
extern int g_TitleNextStage;
extern uint8_t g_FileState;
extern bool g_MainMenuOpen;
extern bool g_CombatSimMode;
extern bool g_IsAnyMenuOpen;
extern struct var80062960 *var80062960;
extern float g_ChrAnimSpeed;
extern int g_SelectedAnimNum;
extern int g_NextChrnum;
extern struct chrdata *g_ChrSlots;
extern int g_NumChrSlots;
extern struct shieldhit *g_ShieldHits;
extern bool g_ShieldHitActive;
extern int g_NumBondBodies;
extern int g_NumMaleGuardHeads;
extern int g_NumFemaleGuardHeads;
extern int g_NumMaleGuardTeamHeads;
extern int g_BondBodies[];
extern int g_MaleGuardHeads[];
extern int g_MaleGuardTeamHeads[];
extern int g_FemaleGuardHeads[];
extern int g_RandomBond;
extern float g_EnemyAccuracyScale;
extern float g_PlayerDamageRxScale;
extern float g_PlayerDamageTxScale;
extern float g_AttackWalkDurationScale;
extern int g_NumChrsSeenPlayerRecently2;
extern struct animtablerow g_DeathAnimsHumanGun[];
extern struct animtablerow g_AnimTableHumanSlumped[];
extern struct animtable *g_AnimTablesByRace[5];
extern struct attackanimconfig var800656c0[];
extern struct attackanimgroup *g_StandHeavyAttackAnims[][32];
extern struct attackanimconfig var80065be0[];
extern struct attackanimgroup *g_StandLightAttackAnims[][32];
extern struct attackanimconfig var800663d8[];
extern struct attackanimgroup *g_StandDualAttackAnims[][32];
extern struct attackanimgroup *g_KneelHeavyAttackAnims[][32];
extern struct attackanimgroup *g_KneelLightAttackAnims[][32];
extern struct attackanimgroup *g_KneelDualAttackAnims[][32];
extern struct attackanimconfig g_RollAttackAnims[];
extern struct attackanimconfig g_WalkAttackAnims[];
extern uint32_t g_StageFlags;
extern struct chrdata *g_BgChrs;
extern int16_t *g_BgChrnums;
extern int g_NumBgChrs;
extern int16_t *g_TeamList;
extern int16_t *g_SquadronList;
extern struct animsmovement *g_MoveAnims[];
extern float g_AutoAimScale;
extern uint32_t g_TintedGlassEnabled;
extern int g_AlarmTimer;
extern struct sndstate *g_AlarmAudioHandle;
extern float g_AlarmSpeakerWeight;
extern float g_GasReleaseTimer240;
extern bool g_GasReleasing;
extern struct coord g_GasPos;
extern int g_GasLastCough60;
extern float g_GasSoundTimer240;
extern struct sndstate *g_GasAudioHandle;
extern uint32_t g_CountdownTimerOff;
extern bool g_CountdownTimerRunning;
extern float g_CountdownTimerValue60;
extern uint32_t g_PlayersDetonatingMines;
extern int g_NextWeaponSlot;
extern int g_NextHatSlot;
extern struct linkliftdoorobj *g_LiftDoors;
extern struct padlockeddoorobj *g_PadlockedDoors;
extern struct safeitemobj *g_SafeItems;
extern struct linksceneryobj *g_LinkedScenery;
extern struct blockedpathobj *g_BlockedPaths;
extern struct prop *g_EmbedProp;
extern int g_EmbedHitPart;
extern float g_CctvWaitScale;
extern float g_CctvDamageRxScale;
extern float g_AutogunAccuracyScale;
extern float g_AutogunDamageTxScale;
extern float g_AutogunDamageRxScale;
extern float g_AmmoQuantityScale;
extern struct padeffectobj *g_PadEffects;
extern int g_LastPadEffectIndex;
extern struct autogunobj *g_ThrownLaptops;
extern struct beam *g_ThrownLaptopBeams;
extern int g_MaxThrownLaptops;
extern struct prop *g_Lifts[10];
extern uint32_t g_TvCmdlist00[];
extern uint32_t g_TvCmdlist1E[];
extern uint32_t g_TvCmdlist1F[];
extern struct pschannel *g_PsChannels;
extern int g_ObjectiveLastIndex;
extern bool g_ObjectiveChecksDisabled;
extern struct weapon *g_Weapons[];
extern bool g_CasingsActive;
extern int g_MaxModels;
extern int g_MaxAnims;
extern bool g_ModelIsLvResetting;
extern int g_ModelMostType1;
extern int g_ModelMostType2;
extern int g_ModelMostType3;
extern int g_ModelMostModels;
extern int g_ModelMostAnims;
extern uint32_t var8007073c;
extern uint32_t var8007074c;
extern bool g_PlayersWithControl[];
extern bool g_PlayerInvincible;
extern bool g_InCutscene;
extern int16_t g_DeathAnimations[];
extern int g_NumDeathAnimations;
extern int g_ScissorX1;
extern int g_ScissorX2;
extern int g_ScissorY1;
extern int g_ScissorY2;
extern char *g_StringPointer;
extern char *g_StringPointer2;
extern int g_MpPlayerNum;
extern uint32_t g_MpNumJoined;
extern uint16_t g_ControlStyleOptions[];
extern struct menudialogdef g_PreAndPostMissionBriefingMenuDialog;
extern struct solostage g_SoloStages[];
extern struct menudialogdef g_SoloMissionControlStyleMenuDialog;
extern struct menudialogdef g_CiControlStyleMenuDialog;
extern struct menudialogdef g_CiControlStylePlayer2MenuDialog;
extern struct menudialogdef g_ChangeAgentMenuDialog;
extern struct menudialogdef g_2PMissionOptionsHMenuDialog;
extern struct menudialogdef g_2PMissionOptionsVMenuDialog;
extern struct menudialogdef g_FrWeaponsAvailableMenuDialog;
extern struct menudialogdef g_SoloMissionPauseMenuDialog;
extern struct menudialogdef g_2PMissionPauseHMenuDialog;
extern struct menudialogdef g_2PMissionPauseVMenuDialog;
extern struct cutscene g_Cutscenes[];
extern struct menudialogdef g_CiMenuViaPcMenuDialog;
extern struct menudialogdef g_CiMenuViaPauseMenuDialog;
extern struct menudialogdef g_CheatsMenuDialog;
extern struct menudialogdef g_PakChoosePakMenuDialog;
extern struct filelist *g_FileLists[MAX_PLAYERS];
extern bool var80075bd0[];
extern struct headanim g_HeadAnims[2];
extern uint8_t unregistered_function1[];
extern uint8_t unregistered_function2[];
extern uint8_t unregistered_function3[];
extern struct ailist g_GlobalAilists[];
extern struct skeleton g_SkelDropship;
extern struct skeleton g_SkelSkShuttle;
extern struct skeleton g_SkelLift;
extern struct skeleton g_SkelCctv;
extern struct skeleton g_SkelTerminal;
extern struct skeleton g_SkelCiHub;
extern struct skeleton g_Skel19;
extern struct skeleton g_SkelAutogun;
extern struct skeleton g_Skel11;
extern struct skeleton g_Skel13;
extern struct skeleton g_Skel18;
extern struct skeleton g_Skel12;
extern struct skeleton g_SkelWindowedDoor;
extern struct skeleton g_Skel17;
extern struct skeleton g_Skel0C;
extern struct skeleton g_SkelLogo;
extern struct skeleton g_SkelPdLogo;
extern struct skeleton g_SkelHoverbike;
extern struct skeleton g_SkelJumpship;
extern struct skeleton g_SkelChopper;
extern struct skeleton g_SkelRope;
extern struct skeleton g_SkelBanner;
extern struct skeleton g_SkelMaianUfo;
extern struct skeleton g_SkelCableCar;
extern struct skeleton g_SkelSubmarine;
extern struct skeleton g_SkelTarget;
extern struct skeleton g_SkelRareLogo;
extern struct skeleton g_SkelWireFence;
extern struct skeleton g_SkelBB;
extern struct modelstate g_ModelStates[NUM_MODELS];
extern int8_t g_PropExplosionTypes[];
extern struct skeleton g_SkelBasic;
extern struct skeleton g_SkelChrGun;
extern struct skeleton g_Skel0B;
extern struct modeldef g_PlayerModeldef;
extern struct skeleton g_Skel20;
extern struct skeleton g_SkelClassicGun;
extern struct skeleton g_SkelCasing;
extern struct skeleton g_Skel06;
extern struct skeleton g_SkelJoypad;
extern struct skeleton g_Skel21;
extern struct skeleton g_SkelLaptopGun;
extern struct skeleton g_SkelK7Avenger;
extern struct skeleton g_SkelFalcon2;
extern struct skeleton g_SkelKnife;
extern struct skeleton g_SkelCmp150;
extern struct skeleton g_SkelDragon;
extern struct skeleton g_SkelSuperDragon;
extern struct skeleton g_SkelRocket;
extern struct skeleton g_Skel4A;
extern struct skeleton g_SkelShotgun;
extern struct skeleton g_SkelFarsight;
extern struct skeleton g_Skel4D;
extern struct skeleton g_SkelReaper;
extern struct skeleton g_SkelMauler;
extern struct skeleton g_SkelDevastator;
extern struct skeleton g_SkelPistol;
extern struct skeleton g_SkelAr34;
extern struct skeleton g_SkelMagnum;
extern struct skeleton g_SkelSlayerRocket;
extern struct skeleton g_SkelCyclone;
extern struct skeleton g_SkelSniperRifle;
extern struct skeleton g_SkelTranquilizer;
extern struct skeleton g_SkelCrossbow;
extern struct skeleton g_SkelTimedProxyMine;
extern struct skeleton g_SkelPhoenix;
extern struct skeleton g_SkelCallisto;
extern struct skeleton g_SkelRcp120;
extern struct skeleton g_SkelHudPiece;
extern struct skeleton g_SkelHand;
extern struct skeleton g_SkelLaser;
extern struct skeleton g_SkelGrenade;
extern struct skeleton g_SkelEcmMine;
extern struct skeleton g_SkelUplink;
extern struct skeleton g_SkelRemoteMine;
extern struct skeleton g_SkelChr;
extern struct skeleton g_SkelSkedar;
extern struct skeleton g_SkelDrCaroll;
extern struct skeleton g_Skel22;
extern struct skeleton g_SkelRobot;
extern struct headorbody g_HeadsAndBodies[152];
extern float g_SkyCloudOffset;
extern float g_SkyWindSpeed;
extern float g_SunAlphaFracs[];
extern int g_SunFlareTimers240[];
extern struct coord g_TeleportToPos;
extern struct coord g_TeleportToUp;
extern struct coord g_TeleportToLook;
extern struct vtxstoretype g_VtxstoreTypes[];
extern int g_ExplosionShakeTotalTimer;
extern int g_ExplosionShakeIntensityTimer;
extern float g_ExplosionDamageTxScale;
extern struct sparktype g_SparkTypes[];
extern bool g_SparksAreActive;
extern struct weatherdata *g_WeatherData;
extern int g_NextShardNum;
extern bool g_ShardsActive;
extern struct font *g_FontNumeric;
extern struct fontchar *g_CharsNumeric;
extern struct font *g_FontHandelGothicXs;
extern struct fontchar *g_CharsHandelGothicXs;
extern struct font *g_FontHandelGothicSm;
extern struct fontchar *g_CharsHandelGothicSm;
extern struct font *g_FontHandelGothicMd;
extern struct fontchar *g_CharsHandelGothicMd;
extern struct font *g_FontHandelGothicLg;
extern struct fontchar *g_CharsHandelGothicLg;
extern bool g_DoRedrawEffect;
extern int g_StageIndex;
extern int16_t g_RoomStreamingBoostTimer;
extern struct drawslot *g_BgSpecialDrawSlot;
extern uint16_t g_BgFrameCount;
extern int g_BgNumPortalCameraCacheItems;
extern float g_PortalMidplaneOffset;
extern struct stagetableentry g_Stages[61];
extern int g_RoomMtxNumSlots;
extern uint32_t g_GfxNumSwaps;
extern int g_NumReasonsToEndMpMatch;
extern int g_MusicEventQueueLength;
extern bool g_MusicNrgIsActive;
extern int g_MusicInterval240;
extern int g_MusicSleepRemaining240;
extern int g_MusicDeathTimer240;
extern int g_MusicAge60;
extern int g_MusicLife60;
extern int g_MusicSilenceTimer60;
extern struct surfacetype *g_SurfaceTypes[15];
extern uint16_t *g_ZbufPtr1;
extern float g_AlmostZero;
extern struct menudialogdef g_2PMissionInventoryHMenuDialog;
extern struct menudialogdef g_2PMissionInventoryVMenuDialog;
extern struct menudialogdef g_MpEndscreenChallengeCheatedMenuDialog;
extern struct menudialogdef g_MpEndscreenChallengeFailedMenuDialog;
extern struct menudialogdef g_MpDropOutMenuDialog;
extern struct mparena g_MpArenas[];
extern struct menudialogdef g_MpWeaponsMenuDialog;
extern struct menudialogdef g_MpPlayerOptionsMenuDialog;
extern struct menudialogdef g_MpControlMenuDialog;
extern struct menudialogdef g_MpPlayerStatsMenuDialog;
extern struct menudialogdef g_MpPlayerNameMenuDialog;
extern struct menudialogdef g_MpLoadSettingsMenuDialog;
extern struct menudialogdef g_MpLoadPresetMenuDialog;
extern struct menudialogdef g_MpLoadPlayerMenuDialog;
extern struct menudialogdef g_MpArenaMenuDialog;
extern struct menudialogdef g_MpLimitsMenuDialog;
extern struct menudialogdef g_MpHandicapsMenuDialog;
extern struct menudialogdef g_MpReadyMenuDialog;
extern struct menudialogdef g_MpSimulantsMenuDialog;
extern struct menudialogdef g_MpTeamsMenuDialog;
extern struct menudialogdef g_MpChallengeListOrDetailsMenuDialog;
extern struct menudialogdef g_MpChallengeListOrDetailsViaAdvChallengeMenuDialog;
extern struct menudialogdef g_MpAdvancedSetupMenuDialog;
extern struct menudialogdef g_MpQuickGoMenuDialog;
extern struct menudialogdef g_MpQuickTeamGameSetupMenuDialog;
extern struct menudialogdef g_MpQuickTeamMenuDialog;
extern struct menudialogdef g_CombatSimulatorMenuDialog;
extern struct menudialogdef g_MpCombatOptionsMenuDialog;
extern struct menudialogdef g_HtbOptionsMenuDialog;
extern struct menudialogdef g_CtcOptionsMenuDialog;
extern struct menudialogdef g_KohOptionsMenuDialog;
extern struct menudialogdef g_HtmOptionsMenuDialog;
extern struct menudialogdef g_PacOptionsMenuDialog;
extern struct menudialogdef g_MpScenarioMenuDialog;
extern struct menudialogdef g_MpQuickTeamScenarioMenuDialog;
extern bool g_MpMatchHasEnded;
extern bool g_MpEnableMusicSwitching;
extern struct mpweapon g_MpWeapons[NUM_MPWEAPONS];
extern struct mphead g_MpHeads[75];
extern struct botprofile g_BotProfiles[18];
extern struct mpbody g_MpBodies[61];
extern struct mppreset g_MpPresets[];
extern uint32_t g_TeamColours[];
extern uint32_t var80087ce4[];
extern uint8_t g_BotCount;
extern struct aibotweaponpreference g_AibotWeaponPreferences[];
extern struct challenge g_MpChallenges[30];
extern uint8_t g_FrIsValidWeapon;
extern int g_FrWeaponNum;
extern uint8_t g_ChrBioSlot;
extern uint8_t g_HangarBioSlot;
extern uint8_t g_DtSlot;
extern uint8_t g_HtScenario;
extern struct vtxstoretype g_VtxstoreTypes[4];
extern struct menudialogdef g_FrWeaponListMenuDialog;
extern struct menudialogdef g_FrTrainingInfoInGameMenuDialog;
extern struct menudialogdef g_FrTrainingInfoPreGameMenuDialog;
extern struct menudialogdef g_FrCompletedMenuDialog;
extern struct menudialogdef g_FrFailedMenuDialog;
extern struct menudialogdef g_BioListMenuDialog;
extern struct menudialogdef g_DtListMenuDialog;
extern struct menudialogdef g_DtDetailsMenuDialog;
extern struct menudialogdef g_DtFailedMenuDialog;
extern struct menudialogdef g_DtCompletedMenuDialog;
extern struct menudialogdef g_HtListMenuDialog;
extern struct menudialogdef g_HtDetailsMenuDialog;
extern struct menudialogdef g_HtFailedMenuDialog;
extern struct menudialogdef g_HtCompletedMenuDialog;
extern struct menudialogdef g_HangarListMenuDialog;

extern struct extplayerconfig g_PlayerExtCfg[MAX_PLAYERS];

extern struct weathercfg g_WeatherConfig[WEATHERCFG_MAX_STAGES];
extern const struct weathercfg g_DefaultWeatherConfig;
extern const struct weathercfg *g_CurWeatherConfig;

extern int g_MenuUsingMouse;
extern int g_MenuKeyboardPlayer;

extern float g_ViShakeIntensityMult;
extern uint32_t g_TexFilter2D;
extern int g_HudCenter;
extern int g_MenuMouseControl;
extern uint32_t g_HudAlignModeL;
extern uint32_t g_HudAlignModeR;
extern int g_PrevFrameFb;
extern int g_BlurFb;
extern int g_BlurFbCapTimer;
extern bool g_BlurFbDirty;
extern int g_TickRateDiv;
extern int g_TickExtraSleep;
extern int g_MusicDisableMpDeath;
extern int g_BgunGeMuzzleFlashes;
extern int g_FileAutoSelect;

extern uint8_t g_MpWeaponSetRandomFilters[NUM_MPWEAPONS];
extern int g_MpWeaponRandomFilterNum;

extern TextData *g_TextMissionData;
extern TextData *g_TextGunData;
extern TextData *g_TextMiscData;
extern TextData *g_TextMPMenuData;
extern TextData *g_TextMPWeaponsData;
extern TextData *g_TextOptionsData;
extern TextData *g_TextPropObjData;
extern TextData *g_TextTitleData;

extern struct fontchar g_HandelGothicData[93]; // HD Handel Gothic
extern struct fontchar *g_CharToRender; // Character to render using the HD font

#define PLAYER_EXTCFG() g_PlayerExtCfg[g_Vars.currentplayerstats->mpindex & 3]
#define PLAYER_DEFAULT_FOV (PLAYER_EXTCFG().fovy)

#define TEX_FILTER_2D g_TexFilter2D
#define ADJUST_ZOOM_FOV(x) ((x) * PLAYER_EXTCFG().fovzoommult)